### ISSUE TITLE
fails to run after installation with error 

### ISSUE THREAD

**Issue by mossplix** [mysociety/fixmystreet#1014]
Couldn't require FixMyStreet::Cobrand::Barnet : Can't locate Locale/gettext.pm in @INC (@INC contains: /Users/mossplix/Projects/fixmystreet/script/../perllib /Users/mossplix/Projects/fixmystreet/script/../commonlib/perllib /Users/mossplix/Projects/fixmystreet/script/../local/lib/perl5/darwin-thread-multi-2level /Users/mossplix/Projects/fixmystreet/script/../local/lib/perl5 /Library/Perl/5.16/darwin-thread-multi-2level /Library/Perl/5.16 /Network/Library/Perl/5.16/darwin-thread-multi-2level /Network/Library/Perl/5.16 /Library/Perl/Updates/5.16.2 /System/Library/Perl/5.16/darwin-thread-multi-2level /System/Library/Perl/5.16 /System/Library/Perl/Extras/5.16/darwin-thread-multi-2level /System/Library/Perl/Extras/5.16 .) at /Users/mossplix/Projects/fixmystreet/script/../commonlib/perllib/mySociety/Locale.pm line 14, from perllib/FixMyStreet/Geocode/Bing.pm line 16, from perllib/FixMyStreet/Cobrand/Default.pm line 7, from perllib/FixMyStreet/Cobrand/UK.pm line 2, from perllib/FixMyStreet/Cobrand/UKCouncils.pm line 2, from perllib/FixMyStreet/Cobrand/Barnet.pm line 2.
[…snip follow-on errors...]
Compilation failed in require at perllib/FixMyStreet/Map.pm line 20, from perllib/FixMyStreet/App.pm line 14, from local/lib/perl5/Catalyst/ScriptRunner.pm line 50.

[tidied up error message for clarity]

**Comment by dracos** [comment]
Hi, thanks for trying out the code. I'm guessing from your quoted text that this is running on a Mac, can you just confirm that? So I assume you have followed the manual installation instructions.

From the error you quote – "Can't locate Locale/gettext.pm" is the important bit – it sounds like you need to install Locale::gettext somehow. Are you using MacPorts or Homebrew? If MacPorts, you could install the p5.16-locale-gettext package, but I'm not sure you are from the above text.

If you're using Homebrew, then the following should hopefully install it for you, from the fixmystreet directory: `bin/cpanm -l local Locale::gettext`.

We haven't previously put Locale::gettext in the default list of Perl modules to install because it can have problems installing as explained at #349, but perhaps we should revisit that if MacPorts is the only platform with an issue and Homebrew is fine.

**Comment by dracos** [comment]
I have just done a fresh install with Homebrew, now that #1016 has been merged. It now seems to work okay, as long as gettext has been installed with brew and linked – `brew install gettext && brew link gettext --force` (or similar for MacPorts). I've updated the documentation accordingly. Please let me know/reopen if you still have issues installing.
