### ISSUE TITLE
Map too large for some mobile devices when viewing a report

### ISSUE THREAD

**Issue by BenJam** [mysociety/fixmystreet#1039]
> Could you please note, however, that the size of the map is too large on my screen and therefore I cannot scroll down to the details below. I have found a work-around whereby I tap the menu icon at the top of the screen. This appears to take me to the bottom of the page, whereupon I can navigate the entirety of the page.

Users device is a Sony Xperia M2 running Android 4.4.4

**Comment by zarino** [comment]
Is this on a report page like https://www.fixmystreet.com/report/410201 ?

Because, on a screen like the Xperia’s (540 × 960 pixels), and subtracting 200px of browser chrome above/below the page content, this is what I'm seeing:

![screen shot 2015-06-19 at 16 11 25](https://cloud.githubusercontent.com/assets/739624/8256271/de133f8e-169d-11e5-975c-d0dc2f9ffe50.png)

The map is tiny. So, something else must be going on.

If JavaScript is disabled, or not running properly for some reason, a non-draggable map is used, which is square, so maybe that's what the user was seeing? But, since it's non-draggable, scrolling past it shouldn't be an issue.

![screen shot 2015-06-19 at 16 14 22](https://cloud.githubusercontent.com/assets/739624/8256325/48d76e94-169e-11e5-86b0-55941dda35e5.png)

**Comment by stevenday** [comment]
Just a drive-by thought, they might be using their phone in landscape? (Not that this is really a problem worth fixing in that case, but it might be an explanation as to why the map fills the screen)

**Comment by zarino** [comment]
@stevenday – The "desktop" FMS styles kick in once the screen's around 768px wide. The Xperia M2’s screen is 900px wide, so in landscape mode I think it would get the "desktop" styles, where the map covers the right half of the screen:

![screen shot 2015-07-24 at 10 05 53](https://cloud.githubusercontent.com/assets/739624/8871210/8333bd78-31eb-11e5-80ef-ea09f77dfc57.png)

I'm only going by the phone's online specs. It's hard to tell for sure without testing it on the actual device.

**Comment by stevenday** [comment]
Doesn't something weird happen with CSS pixel density though, so it might
not be reporting a 900px width? (I don't get the desktop view in landscape
on my Nexus 4 for example, which is technically 1280 x 768px).

**Comment by zarino** [comment]
Yeah, that's what I'm wondering. I can't find reference online as to what the resolution of the M2 is in "display pixels" (or "density independent pixels") rather than the "hardware pixels".

If we assume the M2 has 2px to each 1dp like the iPhone (meaning a usable resolution of 480×270dp), and the browser chrome takes up 50dp of height, leaving only 220dp, the report page would look like this:

![screen shot 2015-07-24 at 10 25 47](https://cloud.githubusercontent.com/assets/739624/8871583/6312dc74-31ee-11e5-8e14-bc16b91e2b4b.png)

Looks quite convincing…

**Comment by zarino** [comment]
That said, why *anyone* would subject themselves to using a website through a letterbox like this is beyond me.

**Comment by dracos** [comment]
Can’t replicate/not sure what was meant, closing.
