### ISSUE TITLE
Prevent $c->cobrand (without pre-set cobrand) from infinite recursion.

### ISSUE THREAD

**Issue by osfameron** [mysociety/fixmystreet#1077]
This can happen if you create a $c from a script, without setting cobrand.  The error message is confusing:

    Deep recursion on subroutine "Catalyst::Request::path" at ...
    Deep recursion on subroutine "Catalyst::Request::base" at ...
    Deep recursion on anonymous subroutine at accessor Catalyst::Request::base ...

Expected behaviour:

 - informative error message about what you've done wrong
 - OR default to first acceptable cobrand from ALLOWED_COBRANDS / default

**Comment by dracos** [comment]
The recursion is taking place because we use SmartURI, and is happening in `Catalyst::Request`, not our code; if you ask for `$c->request->path`, it does the same thing, as `request->uri` is auto-created, base is called, which calls path again. The `path` function is being called in the end by `$c->cobrand` (via cookie session handling), but is not its fault, it is not causing any recursion. Ideally, should probably not have to use `$c` from a script, but in the mean time will patch `Cookie.pm` to handle it more gracefully.
