### ISSUE TITLE
The possibility of quickly mapping a report to a report pin without losing the summary context

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1094]
In the report summary views, the only way to quickly map a report to a pin seems to be to click on the report title, thus navigating away from the summary view to the problem page.

We would be delighted to see that users could quickly find the pin for a given problem just by hovering the mouse pointer over the problem title, like so:

![hover-problem](https://cloud.githubusercontent.com/assets/777056/7219836/8c881d8e-e6b3-11e4-932f-4d0fb4f1c3f1.png)

As you can see in the mock-up above, the appropriate pin changes its color when the problem is hovered. We think that such a feature would add to the usability of the view.

**Comment by jonkri** [comment]
I assume that this could go the other way as well: That the list items lights up when a pin is hovered.

**Comment by zarino** [comment]
As I mentioned to Matthew, I'm a bit worried about using colour to differentiate the hovered pin from any others, because lots of FMS installs already use a variety of coloured pins to represent different report categories/ages.

Here's how it might look using opacity instead, though:

![hover](https://cloud.githubusercontent.com/assets/739624/12356265/9b766858-bb99-11e5-8bea-7ffa3100320c.gif)

**Comment by zarino** [comment]
I've pushed my work so far to branch [1094-link-reports-and-pins](https://github.com/mysociety/fixmystreet/tree/1094-link-reports-and-pins). See the commit message for an outline of the two issues I can't get my head around. Maybe @dracos might be able to work out how to fix them?

**Comment by dracos** [comment]
This is now live :)
