### ISSUE TITLE
Input for design blog post

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1099]
As discussed with @zarino et al: the designers to research existing council sites and create a list of FMS features that provide a better user experience - or indeed, just a list of design features which make FMS highly usable. They don't necessarily have to be in comparison with council offerings.

Myf will then use this as the basis for a blog post.

**Comment by MyfanwyNixon** [comment]
My initial list:
- You don't have to know who's responsible for your problem, and even if you're travelling across the UK you just have to remember FixMyStreet.com
- We don't ask for a name and address up front (Dave already wrote a blog post about that which I can link back to)
- You can report an issue in only a few clicks; we ask for minimal information and everything is on a single page
- Reports are public, so it cuts down on duplicate reports, allows users to see what the pervasive problems are in their area, and provides a forum for discussion
- Users can subscribe to their area so they know what issues are being reported - especially of interest to local councillors or community groups
- We don't put a load of bumph on the first page and make the link to the actual reporting form really small (like lots of councils do)
- With the app you can make a report even when there's no coverage and it'll send it off when you get back to a hot spot

**Comment by zarino** [comment]
@MyfanwyNixon has a pretty good list there. I've spent an afternoon looking at existing reporting sites, and here are a few *additional* thoughts on what I'd argue differentiates FixMyStreet:

**Goal-driven design.** mySociety has a history of focussing products around *what the citizen wants to do* rather than *what they’re forced to do*. As you noted before – if a citizen’s goal is "tell the council about this problem that's causing me pain", why would you stop them doing that and instead force them to fill in their title, first name, last name, phone number, email address, postal address… etc. At best this is poor design. At worst it's an attempt to increase friction such that fewer reports are made. People are much more receptive to entering their details *after* they’ve completed their primary goal of reporting the underlying problem.

**Iterative improvement.** Some people call this *Kaizen* after the Japanese philosophy of *always making something better*. mySociety constantly tests, improves, and re-tests its products. Even co-branded council deployments of FixMyStreet inherit improvements from the core codebase. Usability design does not stand still, and FixMyStreet is guaranteed to evolve as new devices and behaviours become popular.

More specifically, a big bonus is that **we don't require you to know the exact address or postcode of your problem**. Our own testing has shown that many people will search for their own postcode (the only postcode they tend to know!) and then navigate around the map to *retrace their steps* towards the problem they spotted earlier that day. Linked to this is the benefit of having a **nice, large map** that users can drag just like they're used to. It sounds simple—and these days we're so used to Google Maps-style interfaces that it's easy to take for granted—but a number of other reporting systems squeeze their maps (if they have any!) into tiny little square windows, making finding your location much harder, especially for those with visual or motor difficulties.

**The removal of intermediary steps** is also an advantage. It sounds trite, but page loads inevitably make a process feel longer. FixMyStreet essentially has two pages – the postcode search on the homepage, and the reporting page. That's it. We keep the number of actions on the screen at any one time to a minimum (and we're constantly looking to reduce them – see *Iterative improvement* above!) and we try to present upcoming tasks as early as possible rather than hiding them on subsequent pages, to help the user feel in control.

**Comment by MyfanwyNixon** [comment]
Thank you Zarino.

On the back of Ben's internal blog post, I'm wondering whether we might do a similar list but which highlights benefits for councils. Now obviously, happy users are an indirect benefit to councils, but presumably the things that will really excite them are costs, savings, ease of maintenance, etc. 

I'm going to take a look at our competitors again (we first took a look a coupe of years ago) to see what they highlight and also we'll hopefully get some uptake from our invitation to councils to add their suggestions for new features (blog post due to go out shortly).

Meanwhile I will work on drafting this blog post to go along with the other 'your council is non-compliant' posts, but with the understanding that it's going to appeal more to users than councils.

**Comment by MyfanwyNixon** [comment]
Removing the 'design' label because this then becomes more about user-testing and consultation.
