### ISSUE TITLE
Use new filterable report list on fixmystreet.com map pages

### ISSUE THREAD

**Issue by stevenday** [mysociety/fixmystreet#1141]
As per: https://github.com/mysociety/FixMyStreet-Commercial/issues/400#issuecomment-120010233, https://github.com/mysociety/fixmystreet/pull/1134 added a new (optional) filtering feature which fms.com might benefit from.

**Comment by dracos** [comment]
This should also hopefully as mentioned by @stevenday at https://github.com/mysociety/fixmystreet/pull/1155#discussion_r37619497 take the opportunity to tidy up `_list-entry`/_`item` templates, and types of list they can be in (.report-list, .report-list-a, .issue-list-a and so on).

**Comment by dracos** [comment]
Front page list: `section.full-width ul.issue-list-a [report/_item.html]`
All reports list: `section.full-width ul.issue-list-a [reports/_list-entry.html]`
Your reports list: `ul.issue-list-a.full-width [report/_item.html]`
Your reports list (Greenwich/Oxfordshire): `ul.issue-list-a.full-width [reports/_list-entry.html]`
Around page list: `ul.issue-list-a [report/_item.html]`
Around page list (Greenwich/Oxfordshire): `ul.report-list [reports/_list-entry.html]`
Around page list (Bromley): `ul.issue-list-a [reports/_list-entry.html]`

`[reports/_list-entry.html]`: `[report/_item.html]` (with include_lastupdate)
`[reports/_list-entry.html]` (Greenwich/Oxfordshire): `li.pin_colour a.category h3/p`
`[reports/_list-entry.html]` (Bromley): `li.pin_colour a.category.text img.img span small`

`[report/_item.html]`: `li a.text img.img h4 small`
`[report/_item.html]` (Bromley): Same, span rather than h4

`.issue-list` class: List of updates on Your reports page, list of updates on report page.
`.issue-list-a` class: See list above, plus ward list.

**Comment by dracos** [comment]
The report_list CSS, included by Bromley/Greenwich/Oxfordshire, treats `.report-list` and `.issue-list-a` the same, so I'm not sure of the purpose of the `report-list` class.

**Comment by dracos** [comment]
Bromley low level templates are the same, so have combined them.

**Comment by dracos** [comment]
Merged some base/fixmystreet templates, and added the filters to all cobrands. Then tidied it up so that front page has a different template from the map page three, which makes more sense.
