### ISSUE TITLE
Make a default image for opengraph

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/fixmystreet#1184]
Related to #613

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/fixmystreet/pull/1212

**Comment by zarino** [comment]
@dracos – just a thought, to keep this simple, I only made the change for FMS.com (#1212)… but ISTR that the original issue got prioritised because of a very Facebook-heavy cobrand (MakeMyIsland).

Would you prefer me to make the change in the `base` theme, so all cobrands get the wide-format jpg opengraph image?

**Comment by dracos** [comment]
It'd be good if there could be a default image that could be used by everyone, yeah (can keep what you have for fixmystreet.com on top).
