### ISSUE TITLE
Google Map as Map type does not work anymore.

### ISSUE THREAD

**Issue by vannenc** [mysociety/fixmystreet#1215]
It seems that using Google map OL as map type does not work anymore.

**Comment by dracos** [comment]
That's annoying, I wonder what has changed at Google's end to do that :-(
Some of OpenLayers2's examples no longer work, but a couple still do so I am looking to see what exactly they are doing so that they still work. If I can't work it out, then it looks like we could try and do something like http://openlayers.org/en/v3.0.0/examples/google-map.html (putting the OpenLayers layer as a control within a google map), but I'm not sure how straightforward that will be.

**Comment by dracos** [comment]
I have looked into this and found that by pinning the Google API version to 3.20 it works okay. Let me know if it doesn't fix it for you! I have added the capability for you to pick whether the layer starts off in map or hybrid mode also.

**Comment by dracos** [comment]
This has been fixed by upgrading the OpenLayers used by the GoogleOL layer.
