### ISSUE TITLE
Firefox rendering: stretching chevron

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#1256]
Firefox seems to be stretching a the "click a map, over there dude" chevron oddly:

![firefox-chevron](https://cloud.githubusercontent.com/assets/111320/10397058/b30f7d04-6e9d-11e5-8525-83bb5533ef80.png)

FF 41.0.1
Doesn't do this on Chrome or Safari.

**Comment by dracos** [comment]
The SVG is 27x33, with the background size set to 63x33 – Chrome/Safari implement this by keeping the SVG at its size and having space to the right, Firefox appears to stretch the SVG to fill the size. Dunno which is right

**Comment by zarino** [comment]
I think Firefox is actually doing the right thing here. You tell it to set the background image to be 63px wide, so it stretches it to be 63px wide. That's what [the spec](http://www.w3.org/TR/css3-background/#the-background-size) says it should do. I'm not sure why Chrome/Safari *doesn't* stretch it.

Anyway, all this is happening because we want to position the *right edge* of the arrow 40px from the *right edge* of the element. Which isn't possible in CSS.

You could bake that 40px *into* the SVG itself though, by making the SVG itself 63×33px (where the rightmost 40px are just empty).
