### ISSUE TITLE
fail nicely attempting to display report page if report confirmed report has no confirmation date

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#1269]
When working on the Ugandan FMC site, I think I saw `report/_item.html` coping nicely with records that had been confirmed but had no confirmation date (yes: an error from futzing the data directly), but clicking through to the individual report page threw an exception; would be nice to handle that gracefully like the list does, rather than bomb.

Obviously in such a spirit of generosity it would be nice to have similar incorrect states fail gracefully; but due to circumstances, `confirmed` was the one I discovered.

**Comment by dracos** [comment]
This was because the rows had a `whensent` but no `confirmed` (the code doesn't think it should be possible to send a report that hasn't been confirmed). I guess it could use created if confirmed isn't present, though I'm not sure we want to hide problems in the underlying data because then they might be missed and could possibly cause functional issues elsewhere?
