### ISSUE TITLE
Is there a way to connect FMS with Microsoft Dynamics?

### ISSUE THREAD

**Issue by lfalvarez** [mysociety/fixmystreet#1280]
Hey there:
Lately we have been working with a municipality in Chile that uses Microsoft Dynamics as it's CRM and we were wondering if you knew of anyone connecting FMS with it and if there are any tips that we might want to take advantage of?

**Comment by lfalvarez** [comment]
I'm aware of #997 so I guess there is a way. Do you know if there was anything special that the council had to do?

**Comment by dracos** [comment]
I believe the issue of that ticket was because there was no integration, and by moving the co-ordinates to a single line in the email FixMyStreet sent, that made it easier for them to copy and paste the co-ordinates from the email into Dynamics. But there was no code-based integration.

I don't know if Dynamics can support Open311, http://wiki.open311.org/GeoReport_v2/Support/ mentions it but the site it links to is gone. https://www.microsoft.com/en-us/download/details.aspx?id=24004 implies it has web services, but I'm afraid I don't have any more information as to what they are or how you could use them. If there is a way to post data to Dynamics, then a new SendReport plugin can be written in FixMyStreet and used by a body to send reports straightforwardly enough.

**Comment by lfalvarez** [comment]
Thank you!
