### ISSUE TITLE
Open311 request endpoint does not return number of result as per Open311 specs

### ISSUE THREAD

**Issue by leowmjw** [mysociety/fixmystreet#1313]
When using the Open311 endpoint to request reports; it is always limited, even when I specify a wide range of date. Example:

```
https://aduanku.my/open311/v2/requests.xml?jurisdiction_id=aduanku&start_date=2015-01-01&end_date=2016-10-10

```
Is this 20 result limit a hard limit?  Doesn;t the Open311 specs says it will return 1000 results?

**Comment by leowmjw** [comment]
Looking at how the current limit for Open311, output requests seem to have a hard ceiling determined by RSS_LIMIT as per in  **/fixmystreet/perllib/FixMyStreet/App/Controller/Open311.pm**:
```
sub output_requests : Private {
    my ( $self, $c, $criteria, $limit ) = @_;
    $limit = $c->config->{RSS_LIMIT}
        unless $limit && $limit <= $c->config->{RSS_LIMIT};
```

I think it would make more sense to have the specs based higher ceiling **OPEN311_LIMIT=1000** (to match expected Open311 ceiling result) and allowing users to specify a lower limit if desired; as per below:
```
sub output_requests : Private {
    my ( $self, $c, $criteria, $limit ) = @_;
    $limit = $c->config->{OPEN311_LIMIT}
        unless $limit && $limit <= $c->config->{OPEN311_LIMIT};
```

**Comment by dracos** [comment]
Yes, the maximum requests currently uses `RSS_LIMIT` as you say, this is returned in the discovery call under `max_requests`: https://aduanku.my/open311/v2/discovery.xml and is given in the documentation on `/open311`. I'm certainly happy for adding a separate configuration parameter for the Open311 limit as you suggest; it could default to 1000 if not present so that it would work by default without a limit having to be added.

**Comment by leowmjw** [comment]
Thanks @dracos!

**Comment by dracos** [comment]
This should now be done on master.
