### ISSUE TITLE
Revisit mouse scroll behaviour on map

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1326]
I feel the need to record that Google Maps and OpenStreetMap have now trained users to use their middle/scroll mouse button to zoom maps; so now, on FMS, I'm disappointed/bemused when doing that only causes the sidebar to scroll up and down.

**Comment by zarino** [comment]
The scroll wheel causing the page to scroll rather than the map to zoom is a byproduct of the weird way the content of the page (ie: the list in the sidebar) is overlaid on top of the map, which is stretched across the full height and width of the background.

I know @dracos and I have salivated a number of times over drastically simplifying the map page layout, so that it's a lot more conventional, and the map no longer hides beneath the page content.

If we make such a change, then making it so that the page itself no longer scrolls, and instead the content of the sidebar has its own scrollbar, would also mean we can enable the scrollwheel listener on the map and have it zoom as people expect.
