### ISSUE TITLE
How can I use extra field in the detail page for the webAPI?

### ISSUE THREAD

**Issue by loran750** [mysociety/fixmystreet#1331]
Hello

In the mobile application, i need to add an extra field.
I saw there is an extra column in the problem table.

I'm using the web API /report/news/mobile, if I use "extra" param, it does save that param, it's still empty. How is the format ? 

here is the request i do : /report/new/mobile?service=android&title=mytitle&detail=mydetail&category=mycategory&lat=2&lon=48&pc=&extra=mytest

regards

**Comment by dracos** [comment]
Currently, the extra handling code can be found at https://github.com/mysociety/fixmystreet/blob/master/perllib/FixMyStreet/App/Controller/Report/New.pm#L913-L939
As you can see there, it uses any extra data stored on the category selected (which is e.g. returned by an Open311 service discover call, or otherwise manually created in the database) to add elements to extra, then calls the cobrand's process_extras function (which can do whatever it wants), then stores that on the report. So in your case, I would think using your cobrand's process_extras function is the way to go at present, it can look for a new parameter you know and add that; see e.g. the UK.pm cobrand to see what it does there.

I should note that https://github.com/mysociety/fixmystreet/pull/1291 will probably give you an easier way of adding things to extra, if you'd like to wait for that to be sorted/finished.

**Comment by loran750** [comment]
Hello dracos

it worked !
For the record, I've modified 2 files as in https://github.com/mysociety/fixmystreet/pull/1291/files#r52036814
and then in fixmystreet/perllib/FixMyStreet/Cobrand/<mycobrand>.pm , 

`sub process_extras {

    my $self = shift;
    my $c = shift;
    my $body = shift;
    my $extra = shift;

    push @$extra, { name => 'MY FIELD', value => 'MY VALUE' };
}
`

which is what I was looking for (have to modify my value obviously ;)

What is curious is in the "extra" column, i have this value : 

> L1:1,A1:2,T5:value,T8:MY FIELD,T4:name,T8:MY VALUE,

Anyway. I can dig further.

**Comment by dracos** [comment]
If that is all you doing in process_extras, then you don't need any changes from #1291 (I suggest you don't make those changes to make updating the code easier when it is merged).
Yes, the extra column is stored encoded in the database. If it was started now, we would store it as e.g. JSON, but historically it's an encoding called RABX.
