### ISSUE TITLE
Insert donation CTAs at sweet spots in FMS user flow

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1384]
Moving across to individual repos from https://github.com/mysociety/sysadmin/issues/679

Primarily a design issue: latest suggestion is a test where we display donation links only at each site’s pleasure points:
(Edit to add):
- Work out where the pleasure points are in the user flows for our products (I think @MyfanwyNixon did some research on this before?) and put donation links there, with Analytics tracking IDs.
- Make the donation links really persuasive. Think Save The Children or RSPCA level heart-tugging. Get crying children on there. Again, all-out, no shame.
- Put them up for exactly 2 months, as before.
- See whether donations rise.

**Comment by zarino** [comment]
I seem to recall we agreed the best place for this would be on the Questionnaire completion page (assuming you responded that your problem has been fixed), with the "Your issue is on its way to the council" problem confirmation page being another, less ideal, point.

The [questionnaire completion page](https://github.com/mysociety/fixmystreet/blob/6f997f16abba3b649d939f35abd7607076424fa9/templates/web/base/questionnaire/completed.html), and the [problem confirmation page](https://github.com/mysociety/fixmystreet/blob/235701b34251db9b05a148d25664a2ae545ec5c4/templates/web/base/tokens/confirm_problem.html) both currently display the [`next_steps.html`](https://github.com/mysociety/fixmystreet/blob/98c4305003a7fdd468822cd45a605dd935943f72/templates/web/fixmystreet.com/next_steps.html) template, which includes suggestions for you to:

* Use the FMS app next time
* Share your report / FMS in general, on Twitter and Facebook
* Download FMS "goodies" (the school information packs, poop flags, etc)

We could temporarily replace one (or all) of these with a donation prompt. Then it would appear not only on the problem confirmation page, and questionnaire completion page, but also a bunch of other "yay, you did something!" pages, like the page you see after you send a contact form, after you log out, and after you confirm you’d like to receive an email alert.

**Comment by MyfanwyNixon** [comment]
@zarino - good idea. I may be wrong but I don't think we're really pushing the app so much at the moment? So that could be a good one to replace.

**Comment by zarino** [comment]
Here’s the wording at the moment:

![screen shot 2017-08-16 at 17 08 33](https://user-images.githubusercontent.com/739624/29373269-94549c28-82a5-11e7-980d-ff6683bc0993.png)

If we replace the FMS app advert with a donation prompt, just for the duration of the experiment, what wording would you suggest, @MyfanwyNixon?

**Comment by MyfanwyNixon** [comment]
How about:
# Help support FixMyStreet
FixMyStreet is a free service provided by the charity mySociety. Your donations help keep it that way.

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/fixmystreet/pull/1810
