### ISSUE TITLE
Use of the "flowed" e-mail format

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1393]
Outgoing e-mail (for FixaMinGata) as the following <code>Content-Type</code>:

    Content-Type: text/plain; charset="iso-8859-1"

Furthermore, lines are wrapped around column 78 in the FixaMinGata (and FixMyStreet) templates. On smaller displays, the lines can be wrapped in the middle of the line (imagine something like 60 characters fitting on one line), and on larger displays this makes the text too narrow.

I was wondering if it wouldn't make sense to <strong>not</strong> to wrap lines in the e-mail templates, and use <a href="http://joeclark.org/ffaq.html">the "flowed" format</a> instead, letting e-mail clients rewrap the lines according to the available space in the client.

If I'm reading the spec right (I'm not totally sure), we could change the header to

    Content-Type: text/plain; charset="iso-8859-1"; format="flowed"

and simply let the lines flow.

What do you think about this?

Have a great weekend, everyone!

**Comment by dracos** [comment]
It's not as simple as that, I'm afraid; when you use format=flowed, you must still wrap the lines as normal, but (basically) you end any line that is within a paragraph with a space so that it knows it should combine them at the receiving end. It would be easiest code-wise to do this in the email templates, but that wouldn't handle data added, e.g. report descriptions, so it would probably be better for it to be done programmatically by the code that sends email, so that you don't have to remember to do it :)

**Comment by jonkri** [comment]
I think it makes sense to do it programmatically, like you said. This could allow us to write the e-mail templates in a more natural way (perhaps even using something like Markdown, opening up for generating HTML e-mail for clients that supports it, giving the e-mail a more attractive design).

**Comment by edent** [comment]
As a user, this is what the emails I receive look like.

![pothole](https://cloud.githubusercontent.com/assets/837136/15800794/42c93e8c-2a7b-11e6-91f2-3f323e9086cc.png)

This results in an unpleasant reading experience especially on mobile and other devices with narrow viewports. 

See also https://github.com/mysociety/alaveteli/issues/3065  and the subsequent fix at https://github.com/mysociety/alaveteli/pull/3083

**Comment by dracos** [comment]
Yes, that's an example of what @jonkri said in the original report. I agree; now that #1366 and #1413 have been done, this ticket is easier. I've changed it in 1cddfa67f21e876b90078af40f6b1c589315d451 to just rely on quoted-printable soft line wrapping rather than format=flowed, as I think its fallback is slightly less messy (not much in it anyway).
