### ISSUE TITLE
Better print support for Firefox

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1394]
As discussed in #72, the print support for Firefox (the main FOSS browser) is not as good as in the (proprietary and WebKit-based) browsers Chrome and Safari. [Here](https://github.com/mysociety/fixmystreet/files/248537/FMS.pdf) and [here](https://github.com/mysociety/fixmystreet/files/248538/FMS2.pdf) are two report prints, one of FixMyStreet UK and the other from FixMyStreet Zürich.

**Comment by dracos** [comment]
Chromium (FOSS) has as good print support as Chrome, looks like; it seems that Firefox does not have as good printing support :-/ I have just pushed an improvement that gets rid of the big gap at the start (due to the floating of .content, I don't really understand why!), which would be the main issue here. The bottom of the form still disappears, which is Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=471015 dating from 2008…

**Comment by jonkri** [comment]
Thanks, Matthew! :)
