### ISSUE TITLE
Investigate/improve RSS compatibility with Facebook

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1395]
Via user feedback:

> I use your RSS feed to post relevant FixMyStreet reports on
Facebook via twitterfeed. Trouble is that the feed is not compatible
with Facebook and viewing is a problem. In the good old days, RSS
Graffiti did a great job of feeding to Facebook but they have ceased
operating. Is there anything you can do to update the feed content
so it is compatible?

**Comment by dracos** [comment]
I've signed up for Twitter feed and linked it with Twitter and it's posted an RSS feed entry okay, so I think the RSS feed is okay.
Trying to connect a Facebook account just does nothing, so it looks like the problem might be with twitterfeed? Otherwise, will need more info from them about what "compatible with Facebook" and "viewing is a problem" means.
