### ISSUE TITLE
right problem from Tiny.pm

### ISSUE THREAD

**Issue by loran750** [mysociety/fixmystreet#1474]
Hello

I'm receiving that sort of email in the /var/spool/mail/fms, that tells about a rig do you have an idea  :

From fms@xxx Wed Aug  3 18:40:02 2016
Return-Path: <fms@xxx>
X-Original-To: fms
Delivered-To: fms@xxx
Received: by xxx (Postfix, from userid 1000)
        id 4030418591; Wed,  3 Aug 2016 18:40:02 +0200 (CEST)
From: root@xxx (Cron Daemon)
To: fms@xxx
Subject: Cron <fms@xxx> "/var/www/xxx/fixmystreet/commonlib/bin/run-with-lockfile.sh" -n "/var/www/xxx/fixmystreet/send-reports.lock" "/var/www/xxx/fixmystreet/bin/send-reports" || echo "stalled?"
Content-Type: text/plain; charset=UTF-8
X-Cron-Env: <PATH=/usr/local/bin:/usr/bin:/bin>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/fms>
X-Cron-Env: <LOGNAME=fms>
Message-Id: <20160803164002.4030418591@xxx>
Date: Wed,  3 Aug 2016 18:40:02 +0200 (CEST)

mkdir ../upload: **(translated from french) PERMISSION NOT ALLOWED** at /var/www/xxx/fixmystreet/bin/../local/lib/perl5/Path/Tiny.pm line 396.
stalled?

regards

**Comment by dracos** [comment]
You need to make sure UPLOAD_DIR is set to a location that is writable by the web process (it will try to create it if it doesn't exist, so that would then need permission on the parent directory too, not needed if you create it yourself beforehand). Are you only getting this error in cron, not when someone tries to upload a photo? I'm guessing it's because you have a relative path for the UPLOAD_DIR so when you're running the script from cron it can't find the upload directory and so is erroring. We can probably improve this so that it is relative from the root directory by default if it's not an absolute path, but for now, switching it to an absolute path in your general.yml should fix it.

**Comment by dracos** [comment]
PR at #1481 to make sure UPLOAD_DIR/GEO_CACHE are absolute before use.
