### ISSUE TITLE
MapQuest (API key) support

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1501]
The MapQuest map layer no longer have open API access. FixMyStreet doesn't support the use of API keys for MapQuest, which means that FixMyStreet currently doesn't support MapQuest. The UK Bing layer supports the use of an API key.

**Comment by jonkri** [comment]
We (FixaMinGata) are not quite sure whether we would use MapQuest or OpenStreetMap if we had the choice.

**Comment by dracos** [comment]
Sadly it's not just a matter of API key access, like with Bing; MapQuest now only supports their Leaflet plugin for accessing their tiles, there is no direct tile API/access. So you'd have to change the MapQuest layer to use Leaflet rather than OpenLayers, not a small undertaking! Plus that wouldn't give you non-JS tiles still (theoretically, you /could/ request the JS file server side with the key and get the URL out of that, and then use that server side and indeed client side but not very pretty).

**Comment by jonkri** [comment]
MapQuest is no longer relevant for us, so I'm closing this issue.
