### ISSUE TITLE
[fixmystreet.com] Site performance is steadily getting worse

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#1799]
I've noticed that the site is becoming quite sluggish to use lately. Some of this might be due to the burden on the underlying infrastructure, but part of the problem might be due to the sheer volume of reports. Developing locally with a small database does a good job of hiding the problem, but it becomes apparent when working with a million or so reports in the local DB.

I know this is all a bit vague right now, so let's consider this ticket a placeholder for some more concrete examples.

**Comment by dracos** [comment]
* Admin index page currently shows summary stats that are quite slow to generate, especially on a page you probably want to load quickly. Upwards of 7s in total - 1s problems grouped by state, 1.5s number distinct users, 0.5s updates grouped by state, 1s unsent reports, 2s alert counts, 0.1s contacts 
1s questionnaires grouped by answered. These stats should probably be dropped/moved to a different page (they are already shown on `/status` in fact) or generated some other way.

**Comment by tomoccscholes** [comment]
Keep me in the loop on this. Once you have it up to full speed it would be good to set some page load targets that get checked from time to time (to avoid 'boiling frog' decline).

**Comment by davea** [comment]
Here are a few data points to illustrate the problem. For testing purposes I'm logged in as an inspector-level user.

 - ~9.5s TTFB on report pages, e.g. [this one](https://fixmystreet.oxfordshire.gov.uk/report/1090325). Made worse by lack of feedback whilst waiting for AJAX page load when clicking a report in the map list.
 - ~21s TTFB when loading the duplicate candidates list for a report (e.g. https://fixmystreet.oxfordshire.gov.uk/report/1090331/nearby.json)
 - ~10s TTFB when viewing the /reports page for my categories https://fixmystreet.oxfordshire.gov.uk/reports/Oxfordshire?filter_category=Carriageway%20Defect%2CDrainage%2CMud%20and%20Debris%2CPothole
 - ~8s TTFB when panning/zooming the map on /reports

**Comment by dracos** [comment]
- [ ] Report page when logged in is scanning the entire problem table to find duplicate.
- [ ] Nearby.json is doing a *double* sequence scan (once to filter on id/category/state/non_public, the other doing the 'nearby' filter). THis is because it is looking at a radius of 1000km, rather than 1000m.
- [ ] Report page is only 1.5s in a separate process, so I think there is contention on top. I will add pagination to around shortly which will hopefully reduce that in that processes won't be tied up serving lots of reports.

**Comment by dracos** [comment]
nearby.json is now under a second.

**Comment by tomoccscholes** [comment]
We added resampling on scrolling and zooming which I knew would be a performance hit. Perhaps there could be a delay though, before resampling occurs. If you are trying to drag the map across by two viewport widths you have to wait for the first resample before you can make the second drag.
(Does that make sense? I'm aware I'm not using your terminology...)

**Comment by dracos** [comment]
Yes, that makes sense, and I have noticed the same. I'll certainly look into it, I agree it would be useful to do that if possible.
Performance gets better the more you zoom in, as you'd expect.
Interestingly, as with my last bullet point above, the actual db query+data loads in under a second when I run it in a separate process. Anything above that *appears* (need to do more investigation to check/confirm) to be waiting time for a process to deal with the response, rather than the process of constructing the response itself, so we will look into getting more workers dealing with things if possible (of course, if other things speed up that frees them up quicker to deal with other requests too).

**Comment by dracos** [comment]
around pages now only request the pins once if JavaScript is enabled, after the map is loaded. This makes them much quicker. Duplicate listing/displaying has been considerably sped up.

**Comment by dracos** [comment]
Inspector report page has been sped up considerably by work on the defect type/priority/response template fetching code. Some work on the shortlist code should be going live shortly for speeding up the /reports page.

**Comment by dracos** [comment]
I also did #1817 to further cache body lookups. All the example pages above seem much quicker to me, especially those when logged in that had extreme slowdown recently. I'm not sure it's worth holding open a general ticket like this, so given the improvements I'm seeing, I'm going to close it and any specific issues can be raised as new tickets.

**Comment by tomoccscholes** [comment]
That's fine. Thanks for all your work on it.
