### ISSUE TITLE
Image previews don't work in certain circumstances

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/fixmystreet#1815]
I filled in a report form on FixMyStreet.com - including three images and providing my email address and password. 

Image thumbnails appeared straight away on uploading the images, but on the subsequent confirmation page the image thumbnails were not present; there was just an "X" in what would have been their top right corner. 

Similar occurs when adding a comment with an image. 

Firefox 54.0.1 (64-bit) on OSX

<img width="689" alt="fms-image-bug1" src="https://user-images.githubusercontent.com/547695/29462060-ebb6f5ca-8425-11e7-9a63-987275a1d8c3.png">
<img width="949" alt="fms-image-bug2" src="https://user-images.githubusercontent.com/547695/29462062-ebba49be-8425-11e7-8c43-7c99a518b558.png">

**Comment by RichardTaylor** [comment]
I experience the same issue on my phone:

>Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1

**Comment by dracos** [comment]
Sorry about this; the photos are stored/used okay, it is only the preview of them when showing another page that is not working. I guess it was the upgrade of the library we use in 30dd9d8bd1f4229bf5cb0a8c559ba00dba35b750 at the end of June that broke this somehow, will have to look into why (it is trying to fetch the photo at `/report/undefined` rather than its actual URL).

**Comment by dracos** [comment]
PR at #1819

**Comment by dracos** [comment]
Fix for this should be deployed now.
