### ISSUE TITLE
Display thumbnail of photo before submitting it

### ISSUE THREAD

**Issue by Deborah-mySoc** [mysociety/fixmystreet#190]
It would be good to do this as part of adding a nice image uploader (JS based that started uploading immediately, allowing you to fill in the form whilst it's going etc).

**Comment by zarino** [comment]
Had a quick look into this today.

Reminder: We're aiming for 1) multiple file upload, and 2) image previews for those files.

Assuming we don't want to write our own plugin from scratch, http://www.dropzonejs.com and http://fineuploader.com seem to be the two big players. In IE8–9, Dropzone just falls back to a standard HTML file input, while FineUploader works but without image previews or multiple file selection (ie: it’s no better than a standard HTML file input).

I am a little worried that they're 1) way more fully-featured than we'll ever conceivably use, and 2) not going to support image previews for the 7% of FMS users on IE8–9.

Addressing the first point, I also came across http://www.fyneworks.com/jquery/multifile/ which looks like a much simpler plugin that basically just handles adding/removing files to a list and showing image previews, which is exactly what we want. However, it was last updated in May 2015, and it doesn't specify which browsers it supports. I can see they're using the `FileReader` API to generate the image previews, which is IE10+ only.

So maybe we accept that we're *never* going to get image previews in IE8–9 unless we do it server-side.

**Comment by dracos** [comment]
The fact this page exists https://github.com/blueimp/jQuery-File-Upload/wiki/Browser-support makes me potentially like that option too :) I am happy with fallback in IE less than 10, no worse than it is now. dropzone seems the 'simplest' in terms of one file, quite small, I don't know if that makes it harder to use in any other way, but at first glance. The only thing I can think of is we have the image upload within a whole form of other data, so the JS will need to move out/be handled to a separate form to be uploaded separately, looks like, if I've read the docs right.

**Comment by zarino** [comment]
I have a feeling these ajaxy upload plugins just add complexity in our case (ie: when we’re *already* submitting a form anyway, so including the files as part of that POST is fine).

I'll get a spike going today with Dropzone on the new report page.

**Comment by zarino** [comment]
Now the ajax nature of these libraries makes sense!

I should have already realised this, but – You cannot programmatically add files to an HTML input. Meaning, if libraries want to let you pick multiple files in separate actions (ie: not all at the same time) then they must handle the uploading themselves, rather than acting simply as a nice image picker UI for an existing underlying form. That's why they all require a separate endpoint that accepts just the image payload, and returns a URL or ID for the image, rather than integrating into your existing form.

We have two options:

1. Write an FMS endpoint that accepts the POST payload from one of these libraries (eg: Dropzone) and then returns the image URL for inclusion in the main form data.
   * Advantage: The file(s) can upload in the background, while the user is filling in the rest of the form, which is a nice touch.
   * Disadvantage: Need a new endpoint for accepting files, and a way of saving the URL or ID of previously-uploaded files as part of the existing form handler's behaviour.
2. Write our own module that creates a new HTML file input (inside the existing form) for each image, which are then uploaded along with the rest of the form.
   * Advantage: This would add a new file input for each image you pick, which, IIRC, is how the current concept branch is set up (although I can't find a link – am I imagining it?) and it wouldn't require any new endpoints for accepting file uploads.
   * Disadvantage: We don't get anything for free.

**Comment by dracos** [comment]
Sorry, I probably wasn't clear enough, but I thought "started uploading immediately, allowing you to fill in the form whilst it's going" made it clear that we wanted this to be a separate uploader from the normal form; image preview is a nice to have but it's really the parallel activity that is the main user improvement I think. Your option 1 was always what was going to happen.

**Comment by dracos** [comment]
I don't know of any current concept branch, I'm afraid; Zurich templates have three file input boxes immediately (and main/any cobrand could have similar), but that's all. There is existing very old "partial" upload code for accepting parts of reports separately from the rest, which includes photos, but that will need a bit of work (shouldn't be much hopefully) to only accept photos and give back their temporary URLs.

**Comment by zarino** [comment]
Ok, I'll get Dropzone implemented, as a separate form, and then @dracos you can so the server-side bit for accepting the uploaded files and returning a Dropzone-compatible response.

**Comment by dracos** [comment]
Done for reports, have put updates as #1300.
