### ISSUE TITLE
Possible character encoding problem in 2.2

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1905]
When I'm visiting https://fixamingata.se/around?js=1&pc=orust, the hits are displayed with the appropriate national characters: "Orust, Västra Götalands län, Götaland, Sverige".

However, when I visit the same page on our beta site (https://fixamingata.se/around?js=1&pc=orust, based on HEAD) the hit is shown as "Orust, VÃ¤stra GÃ¶talands lÃ¤n, GÃ¶taland, Sverige".

Has something changed in regard to this lately?

I reverted my changes in https://github.com/jonkri/fixmystreet/commit/7ed9770031b20b304722ffa50850c97bc476307f, but the problem still occurred.

Thanks!

**Comment by dracos** [comment]
The display of results from the geocoder was broken in https://github.com/mysociety/fixmystreet/commit/5934b383754a2d298100a674a1ccefc2cb9e50af, part of https://github.com/mysociety/fixmystreet/pull/1871 – because I did not know about a bug in HTTP::Message, https://github.com/libwww-perl/HTTP-Message/issues/72 (originally reported in 2013; I've submitted a PR at https://github.com/libwww-perl/HTTP-Message/pull/90). I've submitted a PR at #1906 that hopefully fixes this. Note that double-encoded data will have been saved in the cache, so that will need clearing too once the fix is deployed.

**Comment by jonkri** [comment]
Wonderful, it works now, thank you. :)
