### ISSUE TITLE
Osm.fixmystreet.com redirects to www.fixmystreet.com

### ISSUE THREAD

**Issue by hferee** [mysociety/fixmystreet#1995]
When selecting a report on osm.fixmystreet.com, the user is redirected to www.fixmystreet.com.
This causes mainly two problems: 
- the map changes from bing to osm, which is confusing.
- the user may be authenticated on the osm website but not on the www website, and should expect to stay authenticated all along their use of the platform.

**Comment by dracos** [comment]
Thanks for the report. After a quick look, this is because the report links are absolute (using `BASE_URL`, so `www.`) due to the fact that on some installations (e.g. two-tier councils) some reports will be linking to a different site, some will not. And it shares the function with one used in emails for providing a base URL domain there.
Possible solutions:
* Make a new web-template function (`url_for_report`?) that can be used for report URIs that can be relative or absolute - worry there is missing something;
* Make `osm` its own cobrand (a subclass of `fixmystreet` presumably) with its own base URL (but not assets etc) – this would mean it would even stick through email confirmation. Not sure if there are any issues with this, shouldn't be;
* Adding a filter at the end of the request process to change any `www.` links in the output HTML to `osm.` – this is hacky but would definitely catch any other absolute links as well. But feels a bit yucky.
