### ISSUE TITLE
Define FixMyStreet port

### ISSUE THREAD

**Issue by Dylanderv** [mysociety/fixmystreet#1997]
Hi!

I'm deploying FixMyStreet without super user privileges. With nginx I listen to the port 8081.
Then, with a load balancer, I'm redirecting the port 8081 to the port 80 on my route.

The problem is that all the forms tag in the html redirect to the port 8081.

Is there a way to manually configure the port on the config, in order to bypass this redirection and force the use of a particular port?

**Comment by dracos** [comment]
This is not a FixMyStreet issue; if your load balancer sets the correct proxy headings, then the FixMyStreet code will output the correct information.
For example, here is the relevant part of an nginx config when it is listening on port 80 and forwarding on to a FixMyStreet application server:
```
location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto http;
    proxy_pass http://localhost:3000;
}
```
Then running the default development server (on port 3000), I can view the site at http://localhost/ and the forms do not have port 3000 in them.

**Comment by davea** [comment]
You may need to add `using_frontend_proxy: 1` to your `general.yml`, and possibly also include `proxy_set_header X-Forwarded-Port $server_port;` in your nginx config.

**Comment by dracos** [comment]
To explain further when it may be needed, `using_frontend_proxy` will activate the reverse proxy middleware if your `REMOTE_ADDR` is not 127.0.0.1 (when it would be activated automatically), so that will depend upon your setup (ie whether your nginx and load balancer are on the same machine).

I don't think `X-Forwarded-Port` will do anything unless `X-Forwarded-Host` is also provided, and I don't think that's necessary here with the config I gave as that's changing the `Host` header directly. Might have missed something though :)

**Comment by Dylanderv** [comment]
Only adding `using_frontend_proxy: 1` in `general.yml` fixed it.

Is it documented anywhere? I searched a lot in your documentation, and I didn't found it.
If it isn't, it may be good to add it :)

Thank you.
