### ISSUE TITLE
Comma in Open311 date fields

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#2023]
When making requests to the Open311 endpoints, the date fields `requested_datetime`, `agency_sent_datetime` and `updated_datetime` for FixaMinGata have commas in them, and are therefor not valid ISO 8601 dates.

Here is an example of a date value:

"2018-03-12T17:39:27,277523+01:00"

I would have expected it to be:

"2018-03-12T17:39:27.277523+01:00"

Thank you!

**Comment by dracos** [comment]
Probably reducing to second granularity would be enough :)

**Comment by jonkri** [comment]
I agree. :)

**Comment by dracos** [comment]
I've got a PR in to 'fix' this, but it is annoying that I can't replicate the issue here on either Mac or Linux, even in a Swedish locale all my timestamps have a dot. Could you confirm what OS you're running on (including version), which perl version, and which branch/commit of the code you're running that shows this issue? So I can try and replicate to check there's not something else I need to worry about.

**Comment by jonkri** [comment]
We are running `HEAD` on [this branch](https://github.com/jonkri/fixmystreet/tree/2.3). We are still on Debian 7.11 (Wheezy). The version of Perl is v5.14.2. Thank you!

**Comment by dracos** [comment]
I'm running Wheezy, 5.12.4, same commit, and here's what I get:
```
matthew@wheezy$ curl http://sv.fixamingata.127.0.0.1.nip.io:3000/open311/v2/requests.xml?jurisdiction_id=foo
  <requests>
    <request>
      <agency_responsible>
      </agency_responsible>
      <description>Title: Detail</description>
      <detail>Detail</detail>
      <interface_used>Web interface</interface_used>
      <lat>51</lat>
      <long>-1</long>
      <requested_datetime>2016-07-20T14:54:36.305030+01:00</requested_datetime>
      <requestor_name>Matthew</requestor_name>
      <service_code>Other</service_code>
      <service_name>Other</service_name>
      <service_request_id>19349</service_request_id>
      <status>open</status>
      <title>Title</title>
      <updated_datetime>2016-07-20T14:54:36.305030+01:00</updated_datetime>
    </request>
  </requests>
```
I wonder what differs between the two servers...!

**Comment by dracos** [comment]
There were bugs in perl before 5.20 to do with numeric locale leakage, so I'm totally guessing because my servers don't have sv_SE underlying somewhere, but yours presumably do, at some point the C locale leaks back out and means it's okay for me. Or something, who knows! Anyway, I hope there aren't other points where this kind of thing happens. I'll get the PR merged.
