### ISSUE TITLE
Hide fixed reports by default

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#2098]
> Can you remove pins from the map a time after they've been fixed? I'm seeing some that are years old 

> The location of post code N10 2HR is so over populated with problem flags on the map that it is very difficult to add new problem flag locations in that area. Can you please clear the very old report flags so that new ones can be added?

>  Just wondering if you have a policy for removing older posts, particularly those that are reported as fixed? The map is getting crowded with fault reports, and it can be difficult to find an appropriate blank space in which to pin a new problem, or to see if it has already been reported.

> Is there a way of removing the location symbols relating to old and fixed reports from the map. It is getting very cluttered in places. Many of these relate to problems that are several years old. 

> Would it be possible to make all old & resolved issues/ content invisible ? The site looks a bit too busy and not user-friendly anymore now, I think

> Can you please remove/delet fixed problems after say 6 months because there are locations where it is difficult to report a new problem.

> When using the site it is getting more difficult to place mark an incident as there are so many old issues still on the maps. Surely it would possible to remove fixed incident place markers when entering a new incident. There is no need to show old things that are going back months

> Hi, please could you consider remiving the yellow report icons frim the maps which are older than say 6 months. This is because there are some locations such as the Golders Green war memorial area. This has so many yellow icons that it isnpractically impossible to create a new repor.

>  Can we remove old reports to make space for new

> on some roads , old reports are still on your site , which stops new reports being posted . for example simonsway , near manchester airport , there are so many old reports that it is virtually impossible to report a new one

> When trying to place a new problem on the map very often it is a busy place-ie High St so A) There a a jumble of 'pins' B) a lot of the problems have been cleared and are old. Can the map be cleared of old issues sometime.

> E.G. Faulty streetlight deported 2014 is still showing on the map. The map is very cluttered. Should there be a timeout to remove such flags? The site risks using credibility. It is also difficult to read all flags when there are multiple in close proximity.

> When are the reports removed. Now more people are using the app the there are too many point. Either they need to be removed after a certain amount of time or if they’ve been reported fixed. There are reports from 2014 still showing.

>  Can you take down the jobs that have been fixed it’s very confusing 

> Can issues that have been fixed be removed from the map, it will save a lot of time and encourage more use as the map, especially on the app can become very cluttered. 

> it is impossible to see the map due to historic reports that have been fixed, is it possible to remove them?

> I think it could be a good idea to have a box to tick/button to click, to be able to only see recent reports. Historic reports are interesting to read, and as you have stated in the help section, they are of research value etc. However, when trying to look at an area with lots of pins all in the same place, it becomes hard to see and read them. To have a way to hide reports that are 5 - 10 years old would make it much easier to use.

**Comment by dracos** [comment]
The app doesn't have a way to hide the pins. https://github.com/mysociety/fixmystreet-mobile/issues/175 It really should, regardless of anything else (because even if it were recent & open reports only, there still might be lots of them), and that might at least help some of the above.

I don't think we've got the display right yet, certainly, if ever. We used to only show pins from the past [time] (6 months on .com, 1 month Bromley, other variants too) with a Show/hide old button to also see all older ones. See discussion about that last year at https://github.com/mysociety/fixmystreet/issues/525#issuecomment-309744063 – showing all older ones was potentially very slow/unclear/etc. I switched it to pagination *instead*, not as well, which means it will show up to 100 reports maximum, but yes, those could be really really old unless there's enough recent reports, iyswim.

So hiding fixed reports (with no other change) wouldn't fix the issue of it then showing up to 100 open reports on the map, no matter how old they are.

I would be happy for it to only show open by default, *and* only from the past 6 months, paginated. This could work as now, but if there are less than 100 in past 6 months, it just stops and starts paginating at that point, so you could still click next to continue and see next 100-or-6-months-whichever-is-less. Does that have any downsides anyone can think of?

**Comment by abimysoc** [comment]
100 pins is fine for the 'browse reports in this area' user, but too many for someone who just wants to make a report; maybe we should consider reducing it to more like the 10-20 most recent open issues by default, paginated, with number per page controllable by another filter? i.e. "Show [number] reports with [status] about [category]"

**Comment by dracos** [comment]
If we keep the buttons on the front page from @zarino's current test, it could do different things for the two types... Number per page feels a bit like a "Firefox-style can't decide, make it an option", but it is at least something lots of shopping sites do offer, so is familiar ;) 10-20 most recent is still "too many" if they're all clustered around the area you want to report in, and you don't see 'hide pins'. But yes, could also go lower as another option to consider.

(Oh yes, also mobile app/mobile website has no pagination, so pins-you-see-is-what-you-get currently.)

"too many for someone who just wants to make a report" - not necessarily if you want them to e.g. not miss a duplicate in a busy area (ie lots of recent reports on map but not happening to be the precise place you are). Depends upon the area of course, and again, perhaps more of a sign we should have dupe checking after map clicking somehow, continuing the work started/unfinished in #1677

**Comment by dracos** [comment]
More complicated than it appears - we'll have to switch pagination from "N per page" to "view up to N before this ID, limited to N months" style.
