### ISSUE TITLE
Trying to view a report on mobile has an intermittent flickering bug

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/fixmystreet#2130]
- Open FixMyStreet.com on mobile
- Start a new report
- Click an existing report on the map
- It appears, then closes immediately and the map recenters

Appears to be intermittent, and more likely to happen on the first attempt.

Tested on a Pixel 2, running Android 8.1.0, Chrome browser

**Comment by dracos** [comment]
Yep same here, Chrome 66, Android 6. Think this must be relatively new!

**Comment by zarino** [comment]
Can’t replicate it in Safari or Firefox on iOS (both using the iOS webkit renderer), or Safari 11 or Firefox 60 on macOS.

But it _does_ also happen in Chrome 66 on macOS, when the window is narrow enough to trigger mobile mode.

So looks likely to be a Chrome thing! Will see whether I can work out what’s happening.

**Comment by zarino** [comment]
Causes the flicker:

1. Go to fixmystreet.com at a mobile width, in Chrome
2. Enter location, click "GO"
3. Click a marker
4. Notice how the screen momentarily transforms into the report detail screen, and then switches back to the `/around` screen

Does _not_ cause the flicker:

1. Go to fixmystreet.com at a mobile width, in Chrome
2. Enter location, click "GO"
3. **Drag the map, so that an ajax request to `/around?ajax=1` is sent**
4. Click a marker (original, or newly loaded, it doesn’t matter)
5. Notice the flicker doesn’t happen, and you’re taken to the report details page as expected

**Comment by zarino** [comment]
More detail…

It looks like the `$('#map_sidebar').on('click', '.js-back-to-report-list', function(e) {` handler on line 867 of fixmystreet.js is getting called erroneously, and that is what causes the screen to transform back into the `/around` view (`fixmystreet.display.reports_list`).

**Comment by zarino** [comment]
Aha! This is the line that’s causing it: https://github.com/mysociety/fixmystreet/blob/master/web/js/map-OpenLayers.js#L952

**Comment by zarino** [comment]
Infuriatingly, I can’t reproduce this in Chrome on browserstack, so I can’t work out which version introduced the bug, if indeed it is a bug in Chrome.

It looks like, in Chrome only, `OpenLayers.Control.Click` is getting triggered _after_ the `/report` page has been ajaxed in, and therefore `$('.js-back-to-report-list').length` returns true (as far as the code can tell, we’re on the `/report` page at this point, and we’ve just clicked the map, which means we need to go back to the `/around` map view) which kicks us back to the `/around` view.

**Comment by zarino** [comment]
Firefox (top) vs Chrome (bottom):

![screen shot 2018-06-04 at 14 42 15](https://user-images.githubusercontent.com/739624/40920804-867e7f10-6805-11e8-9180-31782b57fabb.png)
