### ISSUE TITLE
filter_category query parameter does not return all reports

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#2166]
### Description of problem

`filter_category` query parameter does not return all reports.

### Version

2.3.4.

### Steps to reproduce

Visit https://fixamingata.se/reports/Klippans+kommun?ajax=1&filter_category=Gator,%20skyltar%20och%20parkering&sort=updated-desc&p=1&bbox=12.751934920312,55.996038045544,13.751690779688,56.236442780696.

### Actual results

No reports are included in the response.

### Expected results

The report https://fixamingata.se/report/8946 is included in the response.

### How reproducible

Seemingly always.

### Additional information

The report is visible in the list here: https://fixamingata.se/reports/Klippans+kommun. The category was renamed yesterday.

**Comment by dracos** [comment]
I think this must be a bug due to the comma. It looks like the JavaScript is using comma as a separator, and so it is not finding the category name when looking it up server-side (as it thinks it's two categories called "Gator" and " sykltar och parkering"). I'll see why it's using commas and if it's easy to fix, you shouldn't need to change your category name.

**Comment by jonkri** [comment]
Hi!

Thanks for the quick response!

Ah - I suspected the comma, but noticed that reports were showing up when the category "Park, träd och buskage" was selected... but that's because there was a category before which was called "Park". Funny coincidence!

**Comment by dracos** [comment]
PR in #2168
