### ISSUE TITLE
Can't fetch submodules

### ISSUE THREAD

**Issue by chellem** [mysociety/fixmystreet#2202]
Hello,

I can't clone the submodules, it seems that git.mysociety.org is down.

Is there any possibility of resolving that issue?

**Comment by dracos** [comment]
Hi, thanks for your message. I've just done a fresh clone and it worked fine, do you have any more details than "is down"?
```
§ git clone https://github.com/mysociety/fixmystreet
Cloning into 'fixmystreet'...
remote: Counting objects: 106910, done.
remote: Compressing objects: 100% (222/222), done.
remote: Total 106910 (delta 340), reused 384 (delta 277), pack-reused 106411
Receiving objects: 100% (106910/106910), 120.82 MiB | 2.66 MiB/s, done.
Resolving deltas: 100% (74373/74373), done.)   
§ cd fixmystreet/
§ git submodule update --init
Submodule 'commonlib' (git://git.mysociety.org/commonlib) registered for path 'commonlib'
Cloning into '/Users/matthew/temp/fixmystreet/commonlib'...
Submodule path 'commonlib': checked out '20f0ad17b4d0d1a0772690ed5fbfea1581a909cc'
§ 
```

**Comment by chellem** [comment]
Well, from my workplace, am behind a proxy, I thought that was the problem but it's not the case.  I can't clone from git.mysociety.org/commonlib.  Host not found and I think there's a ssl problem on it, right?

**Comment by dracos** [comment]
What output do you get if you do a `git clone git://git.mysociety.org/commonlib` from your command line? As that works fine for me, from a server with no special permissions/access. "Host not found" sounds like an issue with your setup I'm afraid, rather than anything at our end, the host definitely does exist. SSL isn't involved (though as far as I know our setup is fine, our git isn't available over HTTPS if that's what you tried). What does `dig git.mysociety.org` show? We haven't had any other reports. The reason we don't use github for the submodule is to prevent a potential external dependency when deploying but perhaps we need to look at that again.

**Comment by dracos** [comment]
@chellem Did you try any of my debugging suggestions, or have any luck in tracking it down?

**Comment by chellem** [comment]
Output of dig:

`
 ; <<>> DiG 9.10.3-P4-Debian <<>> git.mysociety.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45240
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;git.mysociety.org.		IN	A

;; ANSWER SECTION:
git.mysociety.org.	298	IN	A	46.43.39.75

;; Query time: 238 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Oct 11 16:55:27 +04 2018
;; MSG SIZE  rcvd: 62
`

**Comment by dracos** [comment]
Sounds like something at your end is blocking the port git uses (9418)? That's the only thing I can think of from what you say, if it knows the IP but can't connect on the `git` port. Is there any way you can find out if that's the case?

In the meantime, you can change what URL a submodule uses on initialization as follow:
```
$ git clone https://github.com/mysociety/fixmystreet
$ git submodule init
$ vim .git/config # Alter submodule URL to https://github.com/mysociety/commonlib
$ git submodule update
```
That won't affect the repo at all, but should then work for you.
