### ISSUE TITLE
handlemail should use the Auto-Submitted header

### ISSUE THREAD

**Issue by joesiltberg** [mysociety/fixmystreet#2336]
handlemail currently detects out-of-office and other automatic replies by matching the subject line and body against patterns commonly found in such replies.

In RFC 3834, it is recommended that automatic replies SHOULD include the Auto-Submitted header (set to auto-replied). handlemail could check this as a first step, if no such header is included it could continue using the pattern matching.

When handlemail replies to an email sent to the DO_NOT_REPLY_EMAIL address, it should also set this header.

There may also be other, non-standard, headers to consider, see for instance:

https://stackoverflow.com/questions/9426801/detect-auto-reply-emails-programatically

**Comment by dracos** [comment]
Yes, sounds good.
Note that "The auto-replied keyword [...] MAY be used on Delivery Status Notifications (DSNs) and Message Disposition Notifications (MDNs)," so if that is the case on a particular bounce, and if our bounce detection hasn't parsed that bounce, it would be forwarded on to the report creator rather than the contact email. Given if it's not a bounce but an auto-reply, you want that to happen, I can't see any ideal solution there - I think checking the header is overall better, though, and hoping the user contacts you/us in such a case should it arise.
