### ISSUE TITLE
Way of accessing filters at small widths

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#2366]
On mobile/small widths, you get a full screen map showing only open reports by default, with no way of changing that. There should be a way to see the filters (just bringing them into view should be all that's needed, they're in the page currently already!).

**Comment by zarino** [comment]
I’ve spent a little while this morning looking into the best way of doing this.

The `.report-list-filters-wrapper` is in `#map_sidebar`, behind the `#map_box`, so it’s tricky to position it relative to other (auto-calculated) things in the map box. (We could inject it somewhere else in the DOM, using `fixmystreet.mobile_reporting.apply_ui` / `fixmystreet.mobile_reporting.remove_ui` but that feels like asking for trouble).

We can use `position: fixed` and a `z-index` greater than `0` to bring it in front of the map, though, and position it relative to the screen. Here it is, with `bottom: 0; left: 0; right: 0`…

![Screen Shot 2019-05-29 at 11 08 46](https://user-images.githubusercontent.com/739624/58548894-3a3afa80-8202-11e9-87b5-c023663afa24.png)

I can imagine that animating in nicely from the bottom of the screen. Could feel quite natural. Especially if it were triggered by a link near the bottom of the screen to begin with…

![Screen Shot 2019-05-29 at 11 25 28](https://user-images.githubusercontent.com/739624/58549939-9010a200-8204-11e9-80e5-ebd34df0f689.png)

It’ll be tricky to have the black `#sub_map_links` and white `.report-list-filters-wrapper` flow vertically above/below each other (unless we fake it by calculating absolute heights / positions using JavaScript), so the easiest thing to do is probably just to stack the filters in front, using the `z-index`. If we do that, though, we’ll need a way to close/hide the filters again, since the original trigger button in `#sub_map_links` will be obscured.

One thing I’m a bit worried about is the `multi-select` dropdown menus. They weren’t really intended for mobile use, so if we want to expose them here, I think we should work out a way to make them less fiddly, and also make sure they don’t overflow the bottom of the screen…

![Screen Shot 2019-05-29 at 11 11 30](https://user-images.githubusercontent.com/739624/58549068-99007400-8202-11e9-8984-ead30a0cd00c.png)

Nor the top…

![Screen Shot 2019-05-29 at 11 12 45](https://user-images.githubusercontent.com/739624/58549245-001e2880-8203-11e9-9ce4-67472070ad7a.png)

This feels like a problem we could solve in the multi-select library itself. Maybe it should make a sort of centred popup on narrow screens? Fairly easy to do with `position: fixed` and some centering…

![Screen Shot 2019-05-29 at 11 40 15](https://user-images.githubusercontent.com/739624/58550934-c6e7b780-8206-11e9-87d8-a99c718db355.png)

Since the popup is no longer obviously a dropdown connected to the open/close toggle button, we’d need to add a clear way to close it, maybe with a "Done" button at the bottom?

One final thing – we’ll need to stay aware of the transformation this screen undergoes when you A) click a point on the map, hiding `#sub_map_links` and revealing the "Try again / OK" `#mob_sub_map_links`; and B) when you click "OK" and `#map_box` goes `position: relative` (via the `.above-form` class) and scrolls up off screen. If we’re showing `.report-list-filters-wrapper`, we’ll need to make sure it does a sensible thing during these transitions.
