### ISSUE TITLE
Remove "try again" overlay on mobile?

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#2667]
From #2614:
> I feel we should probably lose the "Try again" overlay entirely, perhaps? So that people can scroll back up the page rather than have to click either this or the "Map" link that they might not realise is a link.

**Comment by dracos** [comment]
I guess the issue/reason to keep this is if you do scroll back up, scrolling is then moving the map, not letting you scroll back to the form... Some sites enforce two-finger scrolling for the map in circumstance like that, but not sure we'd want to do that.

My proposal for this ticket is therefore:
- [ ] Rename "Try again" when you first click map to "Nearby reports". You don't need to click try again in order to try again, you can click the map again or drag the pin, clicking try again is actually more annoying because it takes you back to `around` loading nearby pins and starting the whole thing again which you might well not want.
- [x] Clicking OK does as now, scrolling the page down, changing it to say "Map" and creating a "Try again" modal over the map
- [x] Clicking the "Map" link scrolls the page back up and switches back to "Nearby reports/OK" links (as now, with link name change)
- [ ] Scrolling page up manually and clicking "Try again" does the same as clicking "Map", not as it does now which is as if you've clicked the original "Try again" and goes back to `around`.

I think that has the desired effect I'm after, which is to let people more easily go back to pin movement without having to go all the way back to `around`.
