### ISSUE TITLE
Issue creating bodies and editing bodies.

### ISSUE THREAD

**Issue by dotbm** [mysociety/fixmystreet#2691]
**Describe the bug**
When I create a body I can not edit it as it throws an error.

**To Reproduce**
1. Go to /admin/bodies
2. Click on /admin/body/1
3. See error

**Additional context**
site: http://208.113.134.80
admin is default from the installer script as this is a dev server.

**Comment by dracos** [comment]
Sorry to hear that. You will have to look in your web server's error log to see what the actual error is, as it is not displayed to the public on a production server. That could be e.g. /var/www/208.113.134.80/fixmystreet/logs/error_log or /var/log/nginx/error_log or similar, depends on how you installed it. That should help locate what the issue is, feel free to paste it here once you've found it.
I assume all you did was create the body, and nothing else.

**Comment by dotbm** [comment]
Thank you so much, I had been hunting for the logs.  I have found the issue and its an odd one. 

Anything in my /admin area adds /admin to the lookup for any css files.  The site is looking for /var/www/208.113.134.80/fixmystreet/web/admin/vendor/OpenLayers/theme/default/style.css but that does not exist only /var/www/208.113.134.80/fixmystreet/web/vendor/OpenLayers/theme/default/style.css would work perfect. 

I had the same issue on the main admin site as I had no styling but I just created the folder tree and popped the css there so that I could keep testing. 

My general.yml has this ADMIN_BASE_URL: ''"  I did set it to /admin at the start but I have removed it since and restarted FixmyStreet.

**Comment by dracos** [comment]
You don't need to set TIME_ZONE, unless your server is in a different timezone from the people who will be using the site, I would leave it blank. But if you do need to set it, it needs to be a timezone string, such as "Europe/London" or "Atlantic/Bermuda".

You don't need ADMIN_BASE_URL to be set either, unless you have some odd setup. You certainly don't need to create a copy of a folder tree, that's hiding the problem rather than fixing it :) I would make sure you've restarted it all properly, with a blank ADMIN_BASE_URL and then explain what problem you're having when it's set to blank. The CSS on your admin at present appears to be making requests to the right places, anyway.

**Comment by dotbm** [comment]
Thank you so much for all of your help. I am going to give the sever a full reboot to see if that fixed the /admin issues.

The bodies worked as soon as I removed ADT from the TIME_ZONE.
