### ISSUE TITLE
Assets disappear at maximum zoom on OS MasterMap

### ISSUE THREAD

**Issue by chrismytton** [mysociety/fixmystreet#2835]
Assets disappear at maximum zoom on sites using the MasterMap map layer.

**To Reproduce**

1. Go to https://fix.bexley.gov.uk/report/new?longitude=0.1529159510650684&latitude=51.455160729901294 (works on any site with MasterMap and an assets layer)
2. Select the "Traffic lights" category
3. Zoom in all the way
4. The assets disappear when at maximum zoom, but reappear when you zoom out

**Expected behavior**

Assets should be visible at maximum zoom.

**Screencast**

![asset-zoom-issue](https://user-images.githubusercontent.com/22996/72358459-8466e280-36e4-11ea-96c2-603a61c9c7ad.gif)

**Desktop:**

 - OS: macOS
 - Browser: Reproducible in latest versions of Chrome, Firefox and Safari

**Comment by chrismytton** [comment]
Note: This was actually reported by Peterborough when they were testing the tree asset layer on staging.

**Comment by chrismytton** [comment]
Pull request that should fix this here: https://github.com/mysociety/fixmystreet/pull/2843

**Comment by chrismytton** [comment]
Pull request broke some tests on Northamptonshire, so need to investigate that and try again.

**Comment by dracos** [comment]
I think this was caused because if you specify a min resolution and not a max resolution, it tries to construct all the resolution levels from scaling up from the min resolution (which is not a real resolution if it's 0.00001). When we're setting it to a non-existant low resolution alongside a max resolution, that's for the "check it's in range for display" check, but it is constructing bogus resolutions in the layer, but they're constructed downwards from the (real) max resolution so is okay.
Northants is the only layer not to set max resolution on all layers I think, so doing that would presumably fix it. Or set this default of 0.00001 only if max resolution is set would also work I think, I'll just push that now to run the tests.

**Comment by chrismytton** [comment]
@dracos Thanks, I think I understand now. And looks like that tweak has made the tests pass, hooray!

Do you want to make a PR for that or shall I?

**Comment by dracos** [comment]
Ah, thanks for reminding me, forgot I did this at the end of Friday :) Made a PR now.
