### ISSUE TITLE
Moderation log renders erroneous extra data sent_to diff strangely

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#2837]
If a sent report is edited in the admin, the moderation update on the report page indicates a change in the `sent_to` extra metadata even if no change to the contents of that array. Additionally, the rendering of this diff isn't marked as safe so the rendering is wrong:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/4776/72432005-f5160980-378d-11ea-8abf-203f7d9aa3fb.png">

Steps to reproduce:

 1. Visit the admin page of a report with an email address in its `sent_to` extra metadata
 1. Edit the report title
 1. Visit the public report page
 1. Notice that the "Moderated by an administrator" update shows a change to the extra data as well as the subject, when it should just be the subject that's changed.

**Comment by dracos** [comment]
Also https://www.fixmystreet.com/report/1927134 has `Extra data: <ins style='background-color:#cfc'>closure_alert_sent_at = 1579010921</ins>` on the first update which I guess if it was marked safe would be little better, but it wasn't added during that update, it was added at the time the alert was sent after the *second* update, so it's just wrong/confusing.

**Comment by dracos** [comment]
This is because the latest moderation entry compares its own data to the report itself to see what (it assumed) got changed between the data of the last entry and the report itself, assuming any changes were made by the moderation, even if they were not. This is okay in the case of title/details/photo/anon (moderation or backend admin editing leaves a moderation entry), but is buggy on location/category/extra data changes - e.g. if admin changes location of report or inspector changes category, that change will get "attached" to latest moderation entry, if there is one. Plus any extra data changes made manually or automatically as above. Guess only 'proper' solution is to make sure a moderation entry is added whenever location/category/extra data (where relevant publicly) changes, and skip extra data entries we know don't need to be shown.

**Comment by dracos** [comment]
Somewhat done, for sent_to, would still need list of other fields like closure_alert_sent_at to be compiled.
