### ISSUE TITLE
Improve inspector UI to make it less confusing

### ISSUE THREAD

**Issue by chrismytton** [mysociety/fixmystreet#2901]
> Improve inspector UI to make the dual forms (updates, and inspector) less confusing.

> It’s technically possible for Inspectors to add updates (using the normal update form) with a photo, but it’s not the same part of the form that they use to mark a report as inspected. So maybe that could be improved.

(From the FMS Pro Feature identification session in London, February 2020.)

**Comment by chrismytton** [comment]
This issue is a bit vague at the moment. It came out of the discussions in London in February, but I'm afraid I don't remember any specifics.

@mysociety/fixmystreet What do we want to change about the inspector UI to make it less confusing? Do we want to combine the inspector form with the regular update form? Or perhaps separate the inspector form out onto its own page? Or is this simply about making the current interface a bit clearer? Feels like perhaps this should be a design ticket, if it's about changing the UI/UX?

As a reminder, this is the interface we're talking about, as seen on the Oxfordshire CC cobrand. The "inspector form" is the green column in the middle. The regular update form is on the left.

<img width="1680" alt="Screenshot 2020-04-02 at 16 34 58" src="https://user-images.githubusercontent.com/22996/78537968-31369480-77e8-11ea-9755-e5f530b8c22a.png">

**Comment by dracos** [comment]
Feature-wise, the two forms, if you are a staff user who can see all the bits anyway:
* On the "public" update form (hidden behind "Provide an update" button), you can attach a photo, update text, response templates, change state, and leave update as yourself (though I think body name is actually displayed?), anonymous, or as another user.
* On the inspector form, you can change category, state, extra questions, internal note field, priority, "traffic management", and optionally leave public update text. All updates are left with name of the the body.

So assuming an inspector doesn't need to leave updates anonymously/as another user, you could say that if the ability to attach photos was added to the inspector form, then you could entirely hide the public update form from people who see the inspector form, and then there's no confusion about what form to fill in. (There are smaller versions of the inspector form that would need checking too e.g. if you only have the report_edit_category or _priority permission).

That would seem the easiest solution to me anyway at this point, in terms of something straightforward to do rather than consider larger scale changes?
