### ISSUE TITLE
Update Getopt::Long::Descriptive version

### ISSUE THREAD

**Issue by joesiltberg** [mysociety/fixmystreet#3003]
Some of the scripts uses Getopt::Long::Descriptive. The version currently used prints warnings when using a newer version of Perl (I used Perl 5.28.1):

```
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/(?:[:=][\d\w\+]+[%@]?({ <-- HERE \d*,\d*})?|[!+])$/ at
/var/www/beta.fixamingata.se/fixmystreet/local/lib/perl5/Getopt/Long/Descriptive.pm line 68.
```

Upgrading to the latest version of Getopt::Long::Descriptive seems to fix the issue.

I'd supply a PR but I couldn't figure out how to upgrade a module with Carton properly (if I just added the requirement to the cpanfile, bin/install_perl_modules wouldn't upgrade for me, running `carton update Getopt::Long::Descriptive` worked but made all sorts of changes in cpanfile.snapshot

**Comment by dracos** [comment]
Thanks, I've put in a PR to update it. My process is generally: 1. Put new minimum version in cpanfile. 2. Run the carton install line from install_perl_modules without the `--deployment` flag (your carton update line presumably does the same). 3. Remove all the removals made to cpanfile.snapshot due to differing core modules. I guess technically we should have one snapshot per perl version but it's managed to work okay...

**Comment by joesiltberg** [comment]
Thanks!
