### ISSUE TITLE
systemd service file errors

### ISSUE THREAD

**Issue by l0cKy93** [mysociety/fixmystreet#3038]
FMS Version 3.0.1
Server: Ubuntu Server 18.04.4 LTS
systemd: 237
Fixmystreet is runing behind a nginx proxy.

The provided systemd example service file has some errors and secondly leads to an timeout during boot.
The following adjustments are fixing the errors.
The path to the command /bin/mkdir and /bin/kill must be specified.
ExecStartPre=-mkdir /var/www/fixmystreet/logs 
The - after = indicates that it is not an error if the folder cannot be created because it already exists, which is desirable.

I could not find a fix for the boot error. After boot the service can be started (systemctl start fixmystreet) without error, but fails during boot.

**Comment by joesiltberg** [comment]
I also run fixmystreet behind nginx, but on Debian. Here's my current systemd service file:

```
[Unit]
Description=FixMyStreet Catalyst Application Server
Documentation=https://fixmystreet.org/
After=network.target

[Service]
Type=forking
User=fms
PIDFile=/var/www/fixamingata.se/fixmystreet.pid
ExecStartPre=mkdir -p /var/www/fixamingata.se/logs
ExecStart=/var/www/fixamingata.se/fixmystreet/script/server \
            --port 9000 \
            --env deployment \
            --daemonize \
            --pid /var/www/fixamingata.se/fixmystreet.pid \
            --access-log /var/www/fixamingata.se/logs/fixmystreet.access.log \
            --error-log /var/www/fixamingata.se/logs/fixmystreet.error.log
ExecStop=kill -TERM $MAINPID
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
There was no need for absolute paths to mkdir and kill (so I guess that's Ubuntu specific), and passing `-p` to mkdir makes sure it doesn't fail if the directory exists (and also creates parent directories if needed).

I also had some troubles with timing issues during boot. My issues had to do with the fact that the network wasn't fully up when nginx started and I had some proxy_pass directives in my nginx-config that required a working dns resolver. So far I've worked around it with configuration changes in nginx rather than the systemd service file.

Hope this helps!

**Comment by l0cKy93** [comment]
Thanks for the reply. 
Finally I got the systemd file running during startup. The problem was also a timing error, but in my case the virtual machine caused the error.

**Comment by dracos** [comment]
Glad to hear it; I'll look at getting `-p` added to the mkdir line for that issue. According to https://www.freedesktop.org/software/systemd/man/systemd.service.html the default systemd path should always have things like /bin in it.
