### ISSUE TITLE
Have 500 error on admin/bodies for docker version installation

### ISSUE THREAD

**Issue by biill** [mysociety/fixmystreet#3090]
**Describe the bug**
install docker version of the project, and I navigate to' http://localhost:8000/admin/bodies', error code 500 without any response message in the terminal.

**To Reproduce**
1. clone the repo
2. pull the latest tag image
3. docker-compose up
4.  navigate to admin/bodies, then error code 500

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/8960799/85651849-1f41f080-b677-11ea-9d2f-bf45565110b8.PNG)

**Comment by dracos** [comment]
Thanks for your report; the actual error will have been logged to the server error log, please could you look and include that as otherwise it will be hard to help you.

**Comment by biill** [comment]
I was trying to debug first, and nothing special on the terminal for the logging.

Here is a screenshot of the terminal, thx.


![error](https://user-images.githubusercontent.com/8960799/85719047-13791d00-b6bd-11ea-8e74-9268214795b7.PNG)

**Comment by dracos** [comment]
Is `/admin/bodies` the only page that errors? Are other admin pages okay? Are you logged in or out? If you're not logged in, all that going to `admin/bodies` should do is redirect you to the login page, bit odd if that isn't working. Is the front end (non-admin) okay? If you'

The server logs its errors to `/var/www/fixmystreet/logs/error.log` in the container, so that is where the actual error will be shown if it's not shown on the terminal. Not sure why it wouldn't be showing there - but the bit you quote e.g. doesn't include a line fetching "GET /admin/bodies" so that implies something odd is going on, not sure whether that's with your system or not at this stage though.

**Comment by dracos** [comment]
Alternatively, if you set your STAGING_SITE configuration variable to 1 and restart the app server so that it runs in development mode, you should get a much fuller error message to the browser instead of the multi-language default.

**Comment by biill** [comment]
I think currently for example and general.yml STAGING_SITE all set to 1 already.

**Comment by biill** [comment]
[error] Caught exception in FixMyStreet::App::Controller::Admin::Bodies->body_form_dropdowns "The call to http://localhost:8000/fakemapit/areas/ZZZ at line 15 of FixMyStreet::MapIt failed at /var/www/fixmystreet/fixmystreet/commonlib/perllib/mySociety/MaPit.pm line 82."

seems like in the config file,

**Comment by dracos** [comment]
Aha, that's much more useful, thanks. That looks like a bug somewhere in our Docker setup in that the default `MAPIT_URL` within Docker needs to be set to something to work correctly, which it clearly isn't at preent. If you changed `MAPIT_URL` from `''` to `http://localhost:9000/fakemapit/` (so with the port number of the app server) – hopefully that would work.

I suggest that because please note commenting out/in the lines you reference only makes sense to do if you are developing a site for the UK, because you are now pointing your installation at our live UK installation of MapIt (which also only has a small free tier). The documentation on this setup can be found at https://fixmystreet.org/customising/fms_and_mapit/ hope that's helpful.

**Comment by dracos** [comment]
I've put in a PR at https://github.com/mysociety/fixmystreet/pull/3094 to change the default for Docker to use port 9000 here for initial installation, thanks for letting us know.
