### ISSUE TITLE
Report gets stuck if MapIt `nearest` call fails [1d]

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#3228]
The MapIt `nearest` call in `UK::find_closest` occasionally fails with a "index returned tuples in wrong order" `InternalError`. 
When that happens the report sending daemon appears to get stuck in an infinite loop of attempts to send that report without respecting the back-off based on `send_fail_timestamp` (nor does `send_fail_count` get updated), resulting in excessive cron-mapit emails.

In the past the MapIt error could be avoided by manually shifting the lat/lon of the report a small distance directly in the DB, which would be picked up by the next cron run of `send-reports`. However the send daemon doesn't appear to pick up changes made to the report position, and instead maintains a stale copy of the data meaning the MapIt calls continue to fail.

There appear to be two things required here:

 - Handle errors from `UK::find_closest` and treat it like a normal report failure (e.g. increment `send_fail_count` etc)
 - Ensure the latest DB record is fetched for each send attempt

**Comment by dracos** [comment]
This happened again recently, and shifting the lat/lon in the DB a tiny bit did fix it okay with the daemon at least.

**Comment by ludovic-tc** [comment]
How about automatically tweaking the lat & long values in the DB? Or indeed, in the module?
Which way do we need to tweak them & by how much?

**Comment by dracos** [comment]
That's not known, sometimes a 1e-6 move in one direction is enough, sometimes it isn't. I don't see a particular need for this to be automatically dealt with, it arises rarely and can be looked at as a standard stuck report (we get emailed about them daily), the issue here is more stopping it constantly trying and thereby causing thousands of MapIt error emails to be generated.
