### ISSUE TITLE
 clicking on admin/bodies gives me "mod_fcgid: read data timeout in 40 seconds"

### ISSUE THREAD

**Issue by hgcvm** [mysociety/fixmystreet#3272]
Hello everybody.

I followed the instructions for manual install https://fixmystreet.org/install/manual-install/
I'm currently running in production mode on apache 2.4 
When I try to go to admin and then add bodies (so https://example.com/admin/bodies) I'm getting the following error in Apache error log:

`[Wed Dec 16 20:56:34.176363 2020] [fcgid:warn] [pid 23427] [client x.x.x.x:57902] mod_fcgid: read data timeout in 40 seconds, referer: http://www...........com/admin

[Wed Dec 16 20:56:34.178022 2020] [core:error] [pid 23427] [client x.x.x.x:57902] End of script output before headers: fixmystreet_app_fastcgi.cgi, referer: http://www...........com/admin
`

**Comment by dracos** [comment]
Hi, this might be better placed on our mailing list - https://fixmystreet.org/community/ - as GitHub is generally where we log bugs and feature requests for the software itself, not support queries.

Having said that, my first guess is a MapIt connection issue. To display that page (and assuming from what you say the main admin index was fine), it looks up the various bodies in the database, but also has to connect to your MapIt installation in order to fetch the list of areas to select from when creating a new body. You don't say how you've configured this, so I assume you have not as yet – which should be fine, there is a default fake MapIt included, but I'm not sure if running under mod_fcgid whether the admin page can call out to itself (if you see what I mean) in order to receive the fake MapIt result. This seems like the most plausible explanation for why your server would sit there and then time out after 40s (the mod_fcgid default) anyway, it's awaiting a connection that can never occur because it is waiting for itself to finish. Does it work if you run it as the development server? What is your MAPIT_URL set to? If blank, and you're running behind a proxy of some sort, it's possible the auto-generation of a MAPIT_URL is not working right, you could manually set it to https://example.org/fakemapit/ or whatever and see if that makes a difference. As far as I know, it should certainly be possible to run it like that, Apache can serve more than one request at a time, so I'm not sure what configuration you have that may be causing the issue. Hope that's helpful, anyway.

**Comment by hgcvm** [comment]
Thank dracos for the quick reply and pointing me in the right direction.

I have managed to fix it. It was indeed a mapit issue. Only after configuring 
MAPIT_ID_WHITELIST: [ ] and MAPIT_GENERATION: it worked. Perhaps the mapit connection worked, but just needed too much time. The documentation was actually clear about that.

Sorry, you are right. This was more something for the mailinglist.

**Comment by dracos** [comment]
No worries, glad you worked it out! :)
