### ISSUE TITLE
South Gloucestershire Council

### ISSUE THREAD

**Issue by GreenGloves** [mysociety/fixmystreet#5212]
This is annoying. It used to be a really efficient process. It seems SGC no longer want to acknowledge reports via FixMyStreet as they always used to. I now get this email response;

**Report It page**

For information, there is a council website where members of the public can report many issues online: https://beta.southglos.gov.uk/report/ such as faded road markings, damaged / missing / incorrect road signs etc.

Reporting such requests through the councils website is more efficient, and will ensure the issue is logged and investigated by a highway inspector and then directed to the correct team for any action required. Additionally, reference number for that issue will be provided to track the reported issue. 

Unfortunately, using Fix my street, will only send issues to the councils generic highway email address and will not be as efficient as using the above link. Therefore, if you could please report this through the above link.

Kind regards,

Andrea

Mr Andrea Bonomi

Engineer
Place Engineering
StreetCare, Transport and Waste Services
(Assess & Decide)
South Gloucestershire Council

**Comment by dracos** [comment]
Thanks for your comment. I guess they do at least say it's not as efficient, rather than they're not accepting them at all. This repository is really for issues to do with the codebase rather than our installation of it, so I'm going to close it here, but do send us a message via https://www.fixmystreet.com/contact and we can try and follow it up with them.
