### ISSUE TITLE
Make the 'hide pins' and 'hide old' buttons more prominent.

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#525]
We get a couple of user support queries per month that make it clear the user hasn't seen these - those are obvs just the ones who bother to get in touch. Perhaps a different colour would help.

I also think the 'get updates' button is a little too much on the discreet side.

**Comment by abimysoc** [comment]
User email today asked for this feature to be added, hadn't noticed it was there already!

**Comment by zarino** [comment]
Some thoughts on this:

# Current behaviour

<details>
<summary>Click to expand</summary><p>

Problems are represented by a pin on the map and a corresponding list item in the sidebar. 6 months of problems are shown. Sidebar list items are sorted from newest to oldest, by default, although the user can change this.

A small "Show old" button in the bottom right corner of the map lets you reveal problems older than the 6 month cut-off period. And a similar "Hide pins" button lets you hide all pins on the map.

Clicking the map background begins the process of reporting a new problem. Clicking an existing map pin or sidebar list item brings up details of that report.

Benefits:

* There is a chance that users coming to report a problem at a particular location will notice an existing report for that problem – reducing duplicate reports for the councils to have to process.
* Users can get an impression of how prevalent reports are in an area by just eyeballing the map page.

Drawbacks:

* High concentrations of pins make it hard to click the map to report a new problem.
* "Hide pins" button is easily overlooked.

</p></details>

# Solution 1: Paginate

Paginate the problems so that only, say, 20 problems are shown at a time, sorted as they are now (newest-to-oldest, by default). Buttons in the sidebar will let users navigate back and forth through the pages – Google Maps does this when you search for amenities at a location, although the use-case there is obviously very different.

<details>
<summary>Show benefits and drawbacks</summary><p>

Benefits:

* Only 20 reports will be visible in the sidebar and on the map at any one time, meaning more space to click between pins.
* Rendering of pins on the map when you zoom/scroll will likely be faster, since the javascript is no longer having to request and draw hundreds of problems.

Drawbacks:

* Unlikely that people will click to show more than the first 20 reports – increasing the chances of duplicate reporting if their problem isn’t one of the 20 most recently reported in that area.
* Chance that people won’t notice the pagination links, and just assume they are viewing all reports in an area.

</p></details>

# Solution 2: More prominent "Hide pins" button

Make the "Hide existing reports" button bigger and more obvious – for instance, a large semi-transparent black button, like the pan/zoom controls, floating at the top/centre of the map.

<details>
<summary>Show benefits and drawbacks</summary><p>

Benefits:

* Users who are having difficulty clicking on the map to report a new problem will be more likely to notice there’s a button that will stop the existing pins getting in their way.
* Very quick to implement.

Drawbacks:

* We’re forcing the user to click a button to—from their perspective—make the map usable. They’ve come here to report a problem, why do we then put all these pins in their way?
* Users might not notice the button – no matter how prominent we make it.

</p></details>

# Solution 3: "Report new problem near here" safety net

Accept we cannot prevent people accidentally clicking pins. Instead, when you click an existing report, add a really obvious button to the reporting form, saying something like "Report a different problem at this location".

<details>
<summary>Show benefits and drawbacks</summary><p>

Benefits:

* Helps both people who accidentally click a pin when trying to make a new report *and* people who arrive on an existing report page and want to report a new problem nearby.
* Fairly quick to implement.

Drawbacks:

* People might not notice the new button.
* People might use the new button to "+1" an existing report, resulting in more duplication.

</p></details>

# Solution 4: Force a category selection

Force users to pick a category before we show them reports in an area. (We’ll need to know the location first, to look up the possible list of categories for that area’s body).

<details>
<summary>Show benefits and drawbacks</summary><p>

Benefits:

* Fewer problems displayed at a time, meaning more space to click between pins.
* No impact on preventing duplicate reports – in fact, duplicates might be even less likely, since users will _know_ that all the pins on the map are potential duplicates for the problem they’re about to report.

Drawbacks:

* A major change to the FMS user flow. We’d need to work out where to insert the category selection step in a way that doesn’t lose users.

</p></details>

**Comment by zarino** [comment]
Suggest we:

# 1. Do the quickest possible fix

Move the "Hide pins" button from the small "toolbar" in the bottom right corner of the map, and make it a top level button, like the pan/zoom controls.

# 2. Set up a test for a better solution

A/B test the introduction of a category selection step into the reporting flow, and see whether the extra step reduces conversions.

**Comment by dracos** [comment]
Random notes:
I would say paginate with more than 20 (100 is what `/reports` has). When zoomed in enough, I would consider it more likely that an existing report would be shown (if it's very old, you'd hope either it's been fixed or just abandoned, in which case a "duplicate" isn't so much one). There's the possibility of making sure people have zoomed in enough before letting a 'click' start a new report, although we do try to attempt that with the default zoom level already anyway. Perhaps we could only show open reports by default (I think Oxfordshire does this?). Fixed ones aren't much use unless you're coming not to report an issue immediately, or to complain about one that's not *really* been fixed (which admittedly does appear to happen quite a bit).

I like solution 3 also, particularly as it does help people who come direct to a report page from somewhere else anyway. It's just a reword/moving/addition of the "Problems nearby" link on that page. As you say, it should be quick, so I'd include that in your suggested step 1 if possible.

Some drawbacks to category forcing:
* you have only considered reporting, what will you do for people who wish to view reports in an area, but not report one? Can't people already only view reports in a category using the filter, for example?
* if the categories change, it will probably not be possible to do any nice mapping, they'll just disappear. I understand e.g. Oxfordshire want to reduce their categories in the near future, and I doubt will want people not to see existing reports that just happen to be in a slightly different category.
* what happens when a category still has far too many reports? Broad Street in Birmingham currently shows an unusable number simply in the "Pavements/footpaths" category at the largest zoom level.

I'm happy to do the hide pin/repot page changes, but I think pagination has to be implemented for some locations, and if so, it might as well be seen how it functions everywhere?

**Comment by zarino** [comment]
Here’s a PR for making the "Hide pins" button more prominent: https://github.com/mysociety/fixmystreet/pull/1727 (now larger, and placed next to the zoom/pan controls for greater visibility)

Pagination to 100 reports at a time sounds like a win. @dracos it looks like we already have all the template code and styling for pagination controls, from the `/reports/<body>/<ward>` page – so I’m guessing you can just implement the pagination on `/around` without needing anything else from me?

**Comment by abimysoc** [comment]
With ref to https://github.com/mysociety/fixmystreet/issues/1462#issuecomment-356650895 - some users clearly still aren't registering the new and improved "hide pins" control.

**Comment by abimysoc** [comment]
(see #1098) I'm getting to the point where I could really do with "hide pins" being an option on /my - I've made quite a few reports within 10m of my house...

**Comment by dracos** [comment]
Hide old is gone, and parts of this were done, going to consolidate the actual issue on better named #1462.
