### ISSUE TITLE
Redirect loop from /admin if no from_body is set

### ISSUE THREAD

**Issue by osfameron** [mysociety/fixmystreet#618]
(Discovered while testing -- I'm not sure if users without from_body set occur in the wild?)

It looks like https://github.com/mysociety/fixmystreet/blob/master/perllib/FixMyStreet/App/Controller/Admin.pm#L36 redirects to auth if no from_body is set, but as the user is correctly logged in, it immediately redirects back.

Perhaps the admin page should error instead about an invalid user being logged in?

**Comment by fixmystreetfr** [comment]
the problem still exist and we can't actually update our platforme, did you found any clues to solve it with a quick and simply manner ?

**Comment by dracos** [comment]
Could you please provide more details, as I don't understand precisely what your issue is - what version are you running, what steps do you take, what behaviour do you expect and what happens instead, plus details/link to code of what changes you have made in your cobrand regarding admin login. If you're not running a recent master version, then only http auth people can access the admin, this ticket was specifically about one cobrand.

**Comment by fixmystreetfr** [comment]
i've updated my local repository with git. 
When i connect on "/admin" i've got the prompt for login and password admin authentification as usual but i am redirected to "/auth?r=admin%2F". When i authenticate myself with a user and try to go again to "/admin", i'm redirected to "/my" The admin interface never load.
On our dev server i moved our cobrand and template directory and clone "fixmystreet" repository cobrand and template to check. The same problem is occur. Maybe i forgot some informations about modifications on the admin parts.

**Comment by dracos** [comment]
Hi,
Thanks for the more details! If by "updated my local repository with git" you mean you are now running the master branch, then that is running a new form of admin using the same users as the normal front end, which more graduated permissions. There is a `createsuperuser` script which will create or update a user account to be able to access all areas of the admin; if you run that using `bin/createsuperuser your@email` replacing `your@email` with your user's email address, then it will be upgraded to a superuser and you should be able to log in. Hope that's helpful!

This ticket is actually therefore closed due to chose changes, which we hope to fully document and release soon. I will open a new ticket to say that the admin login should probably show an error if a non-authenticated user logs in to it, rather than just redirecting you to the Your Account page.

**Comment by fixmystreetfr** [comment]
Perfect it's works thanks for the tip.

Sincerely
