### ISSUE TITLE
Email to council includes static map image

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#72]
As an HTML mail, given some people don't seem to follow the link.

**Comment by jonkri** [comment]
Since the problem report web page doesn't print well, and the report e-mail has information not available on the web site, we would like to have the map picture included in the report e-mail. (We are also interested in #1278.)

Even though it would be nice to offer an HTML as an alternative, I guess the image(s) can be attached to a plain text e-mail as a first step, since I'm guessing that would be valuable in itself.

**Comment by dracos** [comment]
Version 1.7 added some improvements to the printing of a report page (see e.g. ae49214).
And there might be more in Zurich cobrand e.g. 319b49f0206fda26d7cf0fdc71eed6c4195594ae that could be brought in, not sure from brief look. But do see if latest version helps at all :)

**Comment by jonkri** [comment]
Ah, I'm noticing some improvements on FixMyStreet. When I print a problem report there (from Firefox), I get a three page document where a small map image is printed on the first page, the upload form on the second page, and the third page only has the footer. (For those that are curious, a print is available [here](https://github.com/mysociety/fixmystreet/files/248503/FMS.pdf).)

Anyway, the important thing for us is to, in the end, make a print of the e-mail a viable and complete document for the people responsible for fixing the problem. The reason the report page won't do is because it doesn't have all the information that the e-mail does.

**Comment by jonkri** [comment]
(Zürich does display the printed report in a somewhat nicer way - on the second page, information about the report is displayed. See a print [here](https://github.com/mysociety/fixmystreet/files/248512/FMS2.pdf). The third page is blank.)

**Comment by dracos** [comment]
Firefox is not as good at printing it seems (or is being more strict, who knows). Things could still be improved, obviously, but other browsers fare a little better: [Chrome](https://github.com/mysociety/fixmystreet/files/248517/PotholesC.-.Viewing.a.problem.__.FixMyStreet.pdf) / [Safari save](https://github.com/mysociety/fixmystreet/files/248519/Potholes.-.Viewing.a.problem.FixMyStreet.pdf)  / [Safari export](https://github.com/mysociety/fixmystreet/files/248520/Potholes2.-.Viewing.a.problem.FixMyStreet.pdf). But anyway, I realise that's something different from this ticket :)

**Comment by jonkri** [comment]
Thanks for the information, Matthew! I created #1394 so that we can track the Firefox printing issue.

**Comment by dracos** [comment]
This has been done.
