### ISSUE TITLE
Change completion page to add new links

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/fixmystreet#972]
Completion page should now:
- Confirm the problem has been sent
- Offer social media sharing (https://github.com/mysociety/fixmystreet/issues/827)
- Advertise the mobile app
- Link to the new Goodies page (https://github.com/mysociety/fixmystreet/issues/971)

**Comment by zarino** [comment]
How’s this for a completion page with equal priority given to the three next steps?

![confirmation-page](https://cloud.githubusercontent.com/assets/739624/5626494/45fa37e2-9584-11e4-8651-7175702105d2.jpg)

This is compared to the current design, [which can be seen here](https://cloud.githubusercontent.com/assets/739624/3555177/5e467f7e-0914-11e4-88df-05f4bcd20b50.png).

Aside from the obvious additions, I’ve also changed the completion message to be more *show* and less *tell*. Rather than thanking them (how quaint!) and telling them where to find the report, it *actually shows them the report*, with a nice clickable title, just like everywhere else on the site. It's also nice to show them their name again.

We might be able to further optimise the flow, as I suggested previously, by combining the logged-in and email-authenticated paths so that they all end on the same confirmation page:

![fms-completion](https://cloud.githubusercontent.com/assets/739624/5626882/35d2229e-9589-11e4-8b44-4d0badf795af.png)

This will increase exposure to the three adverts – which is particularly important for the Goodies page, which we're expecting to be most popular with long-time users who'd probably have accounts, and thus never see the current completion page. @dracos, @hakim, @dave_w – is there a reason we can't/shouldn't do this?

Implementing the new confirmation page design is easy. If we also want to change the flow so that more people see it, I'll need developer help.

**Comment by struan** [comment]
This looks quite busy to me. Also the mobile app icon looks like it's been cut off and makes me think I'm missing something.

I assume for the mobile layout we show them the 'next time use our mobile app' although that might be a bad experience if they're on a platform we don't support...

Also, technically, their report hasn't been sent at that point, it's been queued to be sent. The current wording is 'Your report has been created and will be sent shortly'.

**Comment by zarino** [comment]
Updated version which sorts out some spacing, and drops the mobile icon (I love the hand-drawn icons, but the more I tried to fit it into the space, the more it just looked like clutter – question is, do we miss it now it's gone?)

![confirmation-page](https://cloud.githubusercontent.com/assets/739624/5628473/9f6cd468-959f-11e4-8610-b30c3f21f8a9.jpg)

Also, @struan:

> I assume for the mobile layout we show them the 'next time use our mobile app'

I was simply planning to stack the three boxes on top of each other, with the mobile app one at the top. So yes.

I don't think we should worry too much about advertising iOS/Android apps to people on other operating systems – it happens all over the web, and you never know, people might have *another* phone which does run iOS or Android.

> technically, their report hasn't been sent at that point

If emails in the queue *do* all eventually get sent, I'd argue for saving the end user from technicalities and telling them it's been sent, even if it's still, *technically*, waiting. As far as they're concerned, their interaction has ended. Sending a report to the council was their original goal, so I'd reuse that language as soon as we've got the chance. It's a nicer end point. Do you agree?

**Comment by wrightmartin** [comment]
> If emails in the queue do all eventually get sent, I'd argue for saving the end user from technicalities and telling them it's been sent, even if it's still, technically, waiting. As far as they're concerned, their interaction has ended. Sending a report to the council was their original goal, so I'd reuse that language as soon as we've got the chance. It's a nicer end point. Do you agree?

My thoughts exactly :+1:

**Comment by dracos** [comment]
I do sort of agree, but on the other hand we do get the odd report that won't be sent for some time (e.g. issue with recipient's mail server, Open311 server, what have you), and that's just the sort of text that leads to confused/angry user support on those reports. Also there are a few councils for which we don't send the reports (the user was told this before they left the report). Struan hasn't quoted the right bit of text, though, I think the existing text is okay and might cover your point if slightly reworded, it's currently "&lt;h1>Your problem has been confirmed!&lt;/h1> / Thank you for reporting this issue. [We will now send it to the council.] / You can [view the problem on this site]." Or if it's a council cobranded site, it says "*Your problem has been confirmed!* / Thank you. You have successfully confirmed your report and this will now be investigated by the council. You can [view the problem on this site]. Your reference for this problem is [ID], please quote it in any enquiries."

In terms of the confirmation page advertising things, all looks good to me :) Would be good to get rid of all the Crosssell code as that's not been used for a while and just clutters things up.

**Comment by zarino** [comment]
How about…

**fixmystreet.com:**

![confirmation-normal](https://cloud.githubusercontent.com/assets/739624/5706828/df178514-9a7b-11e4-9a2d-f84feeb3e890.jpg)

**council cobrand:**

![confirmation-council](https://cloud.githubusercontent.com/assets/739624/5706836/e5935148-9a7b-11e4-8ed8-febea403b600.jpg)

(As you can tell, I'm reticent to use "confirmed" as a verb. Is "recorded" suitable? If FMS can't tell me my report has been sent, the least it can do is tell me it's been recorded somewhere, in a passive-aggressive note-taking sense.)

**Comment by wrightmartin** [comment]
"it will be sent to the council shortly" Is a bit vague I think. When? When will my council know about it? When can I talk to them about it? 

'Recorded' could be 'reported'?

**Comment by MyfanwyNixon** [comment]
Yes, recorded makes me feel like no further action will be taken, for some reason.

How about "it's on its way to the council"? Suitably vague, just hinting that the process has started.

**Comment by zarino** [comment]
@MyfanwyNixon @wrightmartin: how about these then?

**fixmystreet.com:**

![confirmation-normal](https://cloud.githubusercontent.com/assets/739624/5719523/52b58f44-9b11-11e4-92cc-77ecfe69226e.jpg)

**Council cobrand:**

![confirmation-council](https://cloud.githubusercontent.com/assets/739624/5719530/5da8bb24-9b11-11e4-8b57-fdaae69fac37.jpg)

**Comment by zarino** [comment]
PS @MyfanwyNixon I love the idea of "on its way" – good balance of what people want (report this damn issue!) and what's actually happening (waiting in a mail queue).

**Comment by wrightmartin** [comment]
'on it's way' is a great solution, nice job @MyfanwyNixon :tada:

**Comment by zarino** [comment]
I've started work on this—including the removal of CrossSell.pm—in [branch 972-completion-adverts](https://github.com/mysociety/fixmystreet/compare/972-completion-adverts?expand=1).

**Comment by zarino** [comment]
For the record, in addition to `tokens/confirm_problem.html`, there are three other "completion" pages that would benefit from similar styling:

* `tokens/confirm_alert.html`
* `tokens/confirm_update.html`
* `questionnaire/completed.html` (which currently looks completely different and very dated)

So I'll make sure the same styles apply to all four pages, for consistency.

**Comment by dracos** [comment]
There's also the contact `submit.html` page.

**Comment by zarino** [comment]
@dracos – Good catch. That one didn't use the crosssell code before, but I guess it makes sense to treat it like the others. Thanks!
